<?php

/**
 * BaseMaintenanceDepositIsolators
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $maintenance_deposit_id
 * @property integer $isolator_id
 * @property MaintenanceDeposit $MaintenanceDeposit
 * 
 * @method integer                     getMaintenanceDepositId()   Returns the current record's "maintenance_deposit_id" value
 * @method integer                     getIsolatorId()             Returns the current record's "isolator_id" value
 * @method MaintenanceDeposit          getMaintenanceDeposit()     Returns the current record's "MaintenanceDeposit" value
 * @method MaintenanceDepositIsolators setMaintenanceDepositId()   Sets the current record's "maintenance_deposit_id" value
 * @method MaintenanceDepositIsolators setIsolatorId()             Sets the current record's "isolator_id" value
 * @method MaintenanceDepositIsolators setMaintenanceDeposit()     Sets the current record's "MaintenanceDeposit" value
 * 
 * @package    bna_green_house
 * @subpackage model
 * @author     Eliezer Talon <elitalon@inventiaplus.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMaintenanceDepositIsolators extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('maintenance_deposit_isolators');
        $this->hasColumn('maintenance_deposit_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('isolator_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('type', 'INNODB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('MaintenanceDeposit', array(
             'local' => 'maintenance_deposit_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}