<?php

/**
 * BaseDnaSequence
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $gen
 * @property date $date
 * @property boolean $worked
 * @property string $remarks
 * @property integer $pcr_id
 * @property Pcr $Pcr
 * @property Doctrine_Collection $Reaction
 * 
 * @method integer             getId()       Returns the current record's "id" value
 * @method string              getGen()      Returns the current record's "gen" value
 * @method date                getDate()     Returns the current record's "date" value
 * @method boolean             getWorked()   Returns the current record's "worked" value
 * @method string              getRemarks()  Returns the current record's "remarks" value
 * @method integer             getPcrId()    Returns the current record's "pcr_id" value
 * @method Pcr                 getPcr()      Returns the current record's "Pcr" value
 * @method Doctrine_Collection getReaction() Returns the current record's "Reaction" collection
 * @method DnaSequence         setId()       Sets the current record's "id" value
 * @method DnaSequence         setGen()      Sets the current record's "gen" value
 * @method DnaSequence         setDate()     Sets the current record's "date" value
 * @method DnaSequence         setWorked()   Sets the current record's "worked" value
 * @method DnaSequence         setRemarks()  Sets the current record's "remarks" value
 * @method DnaSequence         setPcrId()    Sets the current record's "pcr_id" value
 * @method DnaSequence         setPcr()      Sets the current record's "Pcr" value
 * @method DnaSequence         setReaction() Sets the current record's "Reaction" collection
 * 
 * @package    ACM
 * @subpackage model
 * @author     
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDnaSequence extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('dna_sequence');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('gen', 'string', 10, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 10,
             ));
        $this->hasColumn('date', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('worked', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
        $this->hasColumn('remarks', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('pcr_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));

        $this->option('type', 'INNODB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Pcr', array(
             'local' => 'pcr_id',
             'foreign' => 'id'));

        $this->hasMany('PcrReaction as Reaction', array(
             'local' => 'id',
             'foreign' => 'dna_sequence_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}