<?php

/**
 * BaseRegion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $code
 * @property string $name
 * @property integer $country_id
 * @property Country $Country
 * @property Doctrine_Collection $Islands
 * @property Doctrine_Collection $Locations
 * 
 * @method integer             getId()         Returns the current record's "id" value
 * @method string              getCode()       Returns the current record's "code" value
 * @method string              getName()       Returns the current record's "name" value
 * @method integer             getCountryId()  Returns the current record's "country_id" value
 * @method Country             getCountry()    Returns the current record's "Country" value
 * @method Doctrine_Collection getIslands()    Returns the current record's "Islands" collection
 * @method Doctrine_Collection getLocations()  Returns the current record's "Locations" collection
 * @method Region              setId()         Sets the current record's "id" value
 * @method Region              setCode()       Sets the current record's "code" value
 * @method Region              setName()       Sets the current record's "name" value
 * @method Region              setCountryId()  Sets the current record's "country_id" value
 * @method Region              setCountry()    Sets the current record's "Country" value
 * @method Region              setIslands()    Sets the current record's "Islands" collection
 * @method Region              setLocations()  Sets the current record's "Locations" collection
 * 
 * @package    bna_green_house
 * @subpackage model
 * @author     Eliezer Talon <elitalon@inventiaplus.com>
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseRegion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('region');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('code', 'string', 2, array(
             'type' => 'string',
             'fixed' => 1,
             'notnull' => true,
             'length' => 2,
             ));
        $this->hasColumn('name', 'string', 60, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 60,
             ));
        $this->hasColumn('country_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));

        $this->option('type', 'INNODB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Country', array(
             'local' => 'country_id',
             'foreign' => 'id'));

        $this->hasMany('Island as Islands', array(
             'local' => 'id',
             'foreign' => 'region_id'));

        $this->hasMany('Location as Locations', array(
             'local' => 'id',
             'foreign' => 'region_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}