<?php

/**
 * BaseDnaConcentration
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property decimal $amount
 * @property decimal $260_280_ratio
 * @property decimal $260_230_ratio
 * 
 * @method integer          getId()            Returns the current record's "id" value
 * @method decimal          getAmount()        Returns the current record's "amount" value
 * @method decimal          get260280Ratio()   Returns the current record's "260_280_ratio" value
 * @method decimal          get260230Ratio()   Returns the current record's "260_230_ratio" value
 * @method DnaConcentration setId()            Sets the current record's "id" value
 * @method DnaConcentration setAmount()        Sets the current record's "amount" value
 * @method DnaConcentration set260280Ratio()   Sets the current record's "260_280_ratio" value
 * @method DnaConcentration set260230Ratio()   Sets the current record's "260_230_ratio" value
 * 
 * @package    bna_green_house
 * @subpackage model
 * @author     Eliezer Talon <elitalon@inventiaplus.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDnaConcentration extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('dna_concentration');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('amount', 'decimal', null, array(
             'type' => 'decimal',
             'notnull' => true,
             ));
        $this->hasColumn('260_280_ratio', 'decimal', null, array(
             'type' => 'decimal',
             'notnull' => true,
             ));
        $this->hasColumn('260_230_ratio', 'decimal', null, array(
             'type' => 'decimal',
             'notnull' => true,
             ));

        $this->option('type', 'INNODB');
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}