<?php

/**
 * BaseRadiation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property Doctrine_Collection $Samples
 * 
 * @method integer             getId()      Returns the current record's "id" value
 * @method string              getName()    Returns the current record's "name" value
 * @method Doctrine_Collection getSamples() Returns the current record's "Samples" collection
 * @method Radiation           setId()      Sets the current record's "id" value
 * @method Radiation           setName()    Sets the current record's "name" value
 * @method Radiation           setSamples() Sets the current record's "Samples" collection
 * 
 * @package    bna_green_house
 * @subpackage model
 * @author     Eliezer Talon <elitalon@inventiaplus.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRadiation extends sfDoctrineRecord {
    public function setTableDefinition() {
        $this->setTableName('radiation');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 127, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 127,
             ));

        $this->option('type', 'INNODB');
    }

    public function setUp() {
        parent::setUp();
        $this->hasMany('Sample as Samples', array(
             'local' => 'id',
             'foreign' => 'radiation_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}