<?php

/**
 * BaseSampleCollectors
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $sample_id
 * @property integer $collector_id
 * @property Sample $Sample
 * 
 * @method integer          getSampleId()     Returns the current record's "sample_id" value
 * @method integer          getCollectorId()  Returns the current record's "collector_id" value
 * @method Sample           getSample()       Returns the current record's "Sample" value
 * @method SampleCollectors setSampleId()     Sets the current record's "sample_id" value
 * @method SampleCollectors setCollectorId()  Sets the current record's "collector_id" value
 * @method SampleCollectors setSample()       Sets the current record's "Sample" value
 * 
 * @package    ACM
 * @subpackage model
 * @author     
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSampleCollectors extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sample_collectors');
        $this->hasColumn('sample_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('collector_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('type', 'INNODB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Sample', array(
             'local' => 'sample_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}