<?php

/**
 * BaseStrainProperty
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property Doctrine_Collection $Strains
 * @property Doctrine_Collection $StrainProperties
 * 
 * @method integer             getId()               Returns the current record's "id" value
 * @method string              getName()             Returns the current record's "name" value
 * @method Doctrine_Collection getStrains()          Returns the current record's "Strains" collection
 * @method Doctrine_Collection getStrainProperties() Returns the current record's "StrainProperties" collection
 * @method StrainProperty      setId()               Sets the current record's "id" value
 * @method StrainProperty      setName()             Sets the current record's "name" value
 * @method StrainProperty      setStrains()          Sets the current record's "Strains" collection
 * @method StrainProperty      setStrainProperties() Sets the current record's "StrainProperties" collection
 * 
 * @package    ACM
 * @subpackage model
 * @author     
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStrainProperty extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('strain_property');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));


        $this->index('strain_property_name', array(
             'fields' => 
             array(
              'name' => 
              array(
              'length' => 5,
              ),
             ),
             ));
        $this->option('type', 'INNODB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Strain as Strains', array(
             'refClass' => 'StrainProperties',
             'local' => 'property_id',
             'foreign' => 'strain_id'));

        $this->hasMany('StrainProperties', array(
             'local' => 'id',
             'foreign' => 'property_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}