<?php

/**
 * BaseMaintenanceDepositCollectors
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $maintenance_deposit_id
 * @property integer $collector_id
 * @property MaintenanceDeposit $MaintenanceDeposit
 * 
 * @method integer                      getMaintenanceDepositId()   Returns the current record's "maintenance_deposit_id" value
 * @method integer                      getCollectorId()            Returns the current record's "collector_id" value
 * @method MaintenanceDeposit           getMaintenanceDeposit()     Returns the current record's "MaintenanceDeposit" value
 * @method MaintenanceDepositCollectors setMaintenanceDepositId()   Sets the current record's "maintenance_deposit_id" value
 * @method MaintenanceDepositCollectors setCollectorId()            Sets the current record's "collector_id" value
 * @method MaintenanceDepositCollectors setMaintenanceDeposit()     Sets the current record's "MaintenanceDeposit" value
 * 
 * @package    ACM
 * @subpackage model
 * @author     
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMaintenanceDepositCollectors extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('maintenance_deposit_collectors');
        $this->hasColumn('maintenance_deposit_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('collector_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('type', 'INNODB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('MaintenanceDeposit', array(
             'local' => 'maintenance_deposit_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}