<?php
/**
 * Model class
 *
 * acm : Algae Culture Management (https://github.com/singularfactory/ACM)
 * Copyright 2012, Singular Factory <info@singularfactory.com>
 *
 * This file is part of ACM
 *
 * ACM is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * ACM is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with ACM.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @copyright     Copyright 2012, Singular Factory <info@singularfactory.com>
 * @package       ACM.Lib.Model
 * @since         1.0
 * @link          https://github.com/singularfactory/ACM
 * @license       GPLv3 License (http://www.gnu.org/licenses/gpl.txt)
 */


/**
 * BaseMaintenanceDepositRelative
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @property integer $id
 * @property string $name
 * @property integer $maintenance_deposit_id
 * @property MaintenanceDeposit $MaintenanceDeposit
 *
 * @method integer                    getId()                     Returns the current record's "id" value
 * @method string                     getName()                   Returns the current record's "name" value
 * @method integer                    getMaintenanceDepositId()   Returns the current record's "maintenance_deposit_id" value
 * @method MaintenanceDeposit         getMaintenanceDeposit()     Returns the current record's "MaintenanceDeposit" value
 * @method MaintenanceDepositRelative setId()                     Sets the current record's "id" value
 * @method MaintenanceDepositRelative setName()                   Sets the current record's "name" value
 * @method MaintenanceDepositRelative setMaintenanceDepositId()   Sets the current record's "maintenance_deposit_id" value
 * @method MaintenanceDepositRelative setMaintenanceDeposit()     Sets the current record's "MaintenanceDeposit" value
 *
 * @package ACM.Lib.Model
 * @since 1.0
 */
abstract class BaseMaintenanceDepositRelative extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('maintenance_deposit_relative');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('maintenance_deposit_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));

        $this->option('type', 'INNODB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('MaintenanceDeposit', array(
             'local' => 'maintenance_deposit_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}