<?php
/**
 * Model class
 *
 * acm : Algae Culture Management (https://github.com/singularfactory/ACM)
 * Copyright 2012, Singular Factory <info@singularfactory.com>
 *
 * This file is part of ACM
 *
 * ACM is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * ACM is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with ACM.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @copyright     Copyright 2012, Singular Factory <info@singularfactory.com>
 * @package       ACM.Lib.Model
 * @since         1.0
 * @link          https://github.com/singularfactory/ACM
 * @license       GPLv3 License (http://www.gnu.org/licenses/gpl.txt)
 */


/**
 * BaseCollector
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @property integer $id
 * @property string $name
 * @property string $surname
 * @property string $email
 * @property Doctrine_Collection $Samples
 * @property Doctrine_Collection $PatentDeposits
 * @property Doctrine_Collection $MaintenanceDeposits
 * @property Doctrine_Collection $ExternalStrains
 *
 * @method integer             getId()                  Returns the current record's "id" value
 * @method string              getName()                Returns the current record's "name" value
 * @method string              getSurname()             Returns the current record's "surname" value
 * @method string              getEmail()               Returns the current record's "email" value
 * @method Doctrine_Collection getSamples()             Returns the current record's "Samples" collection
 * @method Doctrine_Collection getPatentDeposits()      Returns the current record's "PatentDeposits" collection
 * @method Doctrine_Collection getMaintenanceDeposits() Returns the current record's "MaintenanceDeposits" collection
 * @method Doctrine_Collection getExternalStrains()     Returns the current record's "ExternalStrains" collection
 * @method Collector           setId()                  Sets the current record's "id" value
 * @method Collector           setName()                Sets the current record's "name" value
 * @method Collector           setSurname()             Sets the current record's "surname" value
 * @method Collector           setEmail()               Sets the current record's "email" value
 * @method Collector           setSamples()             Sets the current record's "Samples" collection
 * @method Collector           setPatentDeposits()      Sets the current record's "PatentDeposits" collection
 * @method Collector           setMaintenanceDeposits() Sets the current record's "MaintenanceDeposits" collection
 * @method Collector           setExternalStrains()     Sets the current record's "ExternalStrains" collection
 *
 * @package ACM.Lib.Model
 * @since 1.0
 */
abstract class BaseCollector extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('collector');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 127, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 127,
             ));
        $this->hasColumn('surname', 'string', 127, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 127,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));


        $this->index('collector_name', array(
             'fields' =>
             array(
              'name' =>
              array(
              'length' => 20,
              ),
             ),
             ));
        $this->index('collector_surname', array(
             'fields' =>
             array(
              'surname' =>
              array(
              'length' => 20,
              ),
             ),
             ));
        $this->option('type', 'INNODB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Sample as Samples', array(
             'refClass' => 'SampleCollectors',
             'local' => 'collector_id',
             'foreign' => 'sample_id'));

        $this->hasMany('PatentDeposit as PatentDeposits', array(
             'refClass' => 'PatentDepositCollectors',
             'local' => 'collector_id',
             'foreign' => 'patent_deposit_id'));

        $this->hasMany('MaintenanceDeposit as MaintenanceDeposits', array(
             'refClass' => 'MaintenanceDepositCollectors',
             'local' => 'collector_id',
             'foreign' => 'maintenance_deposit_id'));

        $this->hasMany('ExternalStrain as ExternalStrains', array(
             'refClass' => 'ExternalStrainCollectors',
             'local' => 'collector_id',
             'foreign' => 'external_strain_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}