<?php
/**
 * Model class
 *
 * acm : Algae Culture Management (https://github.com/singularfactory/ACM)
 * Copyright 2012, Singular Factory <info@singularfactory.com>
 *
 * This file is part of ACM
 *
 * ACM is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * ACM is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with ACM.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @copyright     Copyright 2012, Singular Factory <info@singularfactory.com>
 * @package       ACM.Lib.Model
 * @since         1.0
 * @link          https://github.com/singularfactory/ACM
 * @license       GPLv3 License (http://www.gnu.org/licenses/gpl.txt)
 */


/**
 * BasePcrGel
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @property integer $id
 * @property integer $number
 * @property integer $band
 * @property integer $pcr_id
 * @property boolean $is_valid
 * @property Pcr $Pcr
 *
 * @method integer getId()       Returns the current record's "id" value
 * @method integer getNumber()   Returns the current record's "number" value
 * @method integer getBand()     Returns the current record's "band" value
 * @method integer getPcrId()    Returns the current record's "pcr_id" value
 * @method boolean getIsValid()  Returns the current record's "is_valid" value
 * @method Pcr     getPcr()      Returns the current record's "Pcr" value
 * @method PcrGel  setId()       Sets the current record's "id" value
 * @method PcrGel  setNumber()   Sets the current record's "number" value
 * @method PcrGel  setBand()     Sets the current record's "band" value
 * @method PcrGel  setPcrId()    Sets the current record's "pcr_id" value
 * @method PcrGel  setIsValid()  Sets the current record's "is_valid" value
 * @method PcrGel  setPcr()      Sets the current record's "Pcr" value
 *
 * @package ACM.Lib.Model
 * @since 1.0
 */
abstract class BasePcrGel extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('pcr_gel');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('number', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('band', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('pcr_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('is_valid', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));

        $this->option('type', 'INNODB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Pcr', array(
             'local' => 'pcr_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}