<?php
/**
 * Model class
 *
 * acm : Algae Culture Management (https://github.com/singularfactory/ACM)
 * Copyright 2012, Singular Factory <info@singularfactory.com>
 *
 * This file is part of ACM
 *
 * ACM is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * ACM is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with ACM.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @copyright     Copyright 2012, Singular Factory <info@singularfactory.com>
 * @package       ACM.Lib.Model
 * @since         1.0
 * @link          https://github.com/singularfactory/ACM
 * @license       GPLv3 License (http://www.gnu.org/licenses/gpl.txt)
 */


/**
 * BaseProjectName
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @property integer $id
 * @property string $name
 * @property string $description
 * @property string $obligations
 * @property Doctrine_Collection $Projects
 *
 * @method integer             getId()          Returns the current record's "id" value
 * @method string              getName()        Returns the current record's "name" value
 * @method string              getDescription() Returns the current record's "description" value
 * @method string              getObligations() Returns the current record's "obligations" value
 * @method Doctrine_Collection getProjects()    Returns the current record's "Projects" collection
 * @method ProjectName         setId()          Sets the current record's "id" value
 * @method ProjectName         setName()        Sets the current record's "name" value
 * @method ProjectName         setDescription() Sets the current record's "description" value
 * @method ProjectName         setObligations() Sets the current record's "obligations" value
 * @method ProjectName         setProjects()    Sets the current record's "Projects" collection
 *
 * @package ACM.Lib.Model
 * @since 1.0
 */
abstract class BaseProjectName extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('project_name');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 200, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 200,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('obligations', 'string', null, array(
             'type' => 'string',
             ));


        $this->index('project_name_name', array(
             'fields' =>
             array(
              0 => 'name',
             ),
             ));
        $this->option('type', 'INNODB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Project as Projects', array(
             'local' => 'id',
             'foreign' => 'project_name_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}