<?php
/**
 * Model class
 *
 * acm : Algae Culture Management (https://github.com/singularfactory/ACM)
 * Copyright 2012, Singular Factory <info@singularfactory.com>
 *
 * This file is part of ACM
 *
 * ACM is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * ACM is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with ACM.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @copyright     Copyright 2012, Singular Factory <info@singularfactory.com>
 * @package       ACM.Lib.Model
 * @since         1.0
 * @link          https://github.com/singularfactory/ACM
 * @license       GPLv3 License (http://www.gnu.org/licenses/gpl.txt)
 */


/**
 * BaseNotification
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @property integer $id
 * @property string $message
 * @property enum $status
 * @property integer $user_id
 * @property sfGuardUser $User
 *
 * @method integer      getId()      Returns the current record's "id" value
 * @method string       getMessage() Returns the current record's "message" value
 * @method enum         getStatus()  Returns the current record's "status" value
 * @method integer      getUserId()  Returns the current record's "user_id" value
 * @method sfGuardUser  getUser()    Returns the current record's "User" value
 * @method Notification setId()      Sets the current record's "id" value
 * @method Notification setMessage() Sets the current record's "message" value
 * @method Notification setStatus()  Sets the current record's "status" value
 * @method Notification setUserId()  Sets the current record's "user_id" value
 * @method Notification setUser()    Sets the current record's "User" value
 *
 * @package ACM.Lib.Model
 * @since 1.0
 */
abstract class BaseNotification extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('notification');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('message', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('status', 'enum', null, array(
             'type' => 'enum',
             'values' =>
             array(
              0 => 'new',
              1 => 'read',
              2 => 'deleted',
             ),
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));


        $this->index('notification_status', array(
             'fields' =>
             array(
              0 => 'status',
             ),
             ));
        $this->option('type', 'INNODB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}