<?php

/**
 * BaseIsland
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $code
 * @property string $name
 * @property integer $region_id
 * @property Doctrine_Collection $Locations
 * 
 * @method integer             getId()        Returns the current record's "id" value
 * @method string              getCode()      Returns the current record's "code" value
 * @method string              getName()      Returns the current record's "name" value
 * @method integer             getRegionId()  Returns the current record's "region_id" value
 * @method Doctrine_Collection getLocations() Returns the current record's "Locations" collection
 * @method Island              setId()        Sets the current record's "id" value
 * @method Island              setCode()      Sets the current record's "code" value
 * @method Island              setName()      Sets the current record's "name" value
 * @method Island              setRegionId()  Sets the current record's "region_id" value
 * @method Island              setLocations() Sets the current record's "Locations" collection
 * 
 * @package    bna_green_house
 * @subpackage model
 * @author     Eliezer Talon <elitalon@inventiaplus.com>
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseIsland extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('island');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('code', 'string', 2, array(
             'type' => 'string',
             'fixed' => 1,
             'notnull' => true,
             'length' => 2,
             ));
        $this->hasColumn('name', 'string', 60, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 60,
             ));
        $this->hasColumn('region_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));

        $this->option('type', 'INNODB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Location as Locations', array(
             'local' => 'id',
             'foreign' => 'island_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}