<?php
/**
 * Model class
 *
 * acm : Algae Culture Management (https://github.com/singularfactory/ACM)
 * Copyright 2012, Singular Factory <info@singularfactory.com>
 *
 * This file is part of ACM
 *
 * ACM is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * ACM is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with ACM.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @copyright     Copyright 2012, Singular Factory <info@singularfactory.com>
 * @package       ACM.Lib.Model
 * @since         1.0
 * @link          https://github.com/singularfactory/ACM
 * @license       GPLv3 License (http://www.gnu.org/licenses/gpl.txt)
 */


/**
 * BasePatentDepositMaintenanceStatus
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @property integer $patent_deposit_id
 * @property integer $maintenance_status_id
 * @property PatentDeposit $PatentDeposit
 *
 * @method integer                        getPatentDepositId()       Returns the current record's "patent_deposit_id" value
 * @method integer                        getMaintenanceStatusId()   Returns the current record's "maintenance_status_id" value
 * @method PatentDeposit                  getPatentDeposit()         Returns the current record's "PatentDeposit" value
 * @method PatentDepositMaintenanceStatus setPatentDepositId()       Sets the current record's "patent_deposit_id" value
 * @method PatentDepositMaintenanceStatus setMaintenanceStatusId()   Sets the current record's "maintenance_status_id" value
 * @method PatentDepositMaintenanceStatus setPatentDeposit()         Sets the current record's "PatentDeposit" value
 *
 * @package ACM.Lib.Model
 * @since 1.0
 */
abstract class BasePatentDepositMaintenanceStatus extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('patent_deposit_maintenance_status');
        $this->hasColumn('patent_deposit_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('maintenance_status_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('type', 'INNODB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('PatentDeposit', array(
             'local' => 'patent_deposit_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}