<?php

/**
 * BaseHabitat
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $description
 * @property Doctrine_Collection $Samples
 * @property Doctrine_Collection $PatentDeposits
 * @property Doctrine_Collection $MaintenanceDeposits
 * @property Doctrine_Collection $ExternalStrains
 * @property Doctrine_Collection $Isolations
 * 
 * @method integer             getId()                  Returns the current record's "id" value
 * @method string              getName()                Returns the current record's "name" value
 * @method string              getDescription()         Returns the current record's "description" value
 * @method Doctrine_Collection getSamples()             Returns the current record's "Samples" collection
 * @method Doctrine_Collection getPatentDeposits()      Returns the current record's "PatentDeposits" collection
 * @method Doctrine_Collection getMaintenanceDeposits() Returns the current record's "MaintenanceDeposits" collection
 * @method Doctrine_Collection getExternalStrains()     Returns the current record's "ExternalStrains" collection
 * @method Doctrine_Collection getIsolations()          Returns the current record's "Isolations" collection
 * @method Habitat             setId()                  Sets the current record's "id" value
 * @method Habitat             setName()                Sets the current record's "name" value
 * @method Habitat             setDescription()         Sets the current record's "description" value
 * @method Habitat             setSamples()             Sets the current record's "Samples" collection
 * @method Habitat             setPatentDeposits()      Sets the current record's "PatentDeposits" collection
 * @method Habitat             setMaintenanceDeposits() Sets the current record's "MaintenanceDeposits" collection
 * @method Habitat             setExternalStrains()     Sets the current record's "ExternalStrains" collection
 * @method Habitat             setIsolations()          Sets the current record's "Isolations" collection
 * 
 * @package    bna_green_house
 * @subpackage model
 * @author     Eliezer Talon <elitalon@inventiaplus.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseHabitat extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('habitat');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 127, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 127,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             ));


        $this->index('habitat_name', array(
             'fields' => 
             array(
              'name' => 
              array(
              'length' => 20,
              ),
             ),
             ));
        $this->option('type', 'INNODB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Sample as Samples', array(
             'local' => 'id',
             'foreign' => 'habitat_id'));

        $this->hasMany('PatentDeposit as PatentDeposits', array(
             'local' => 'id',
             'foreign' => 'habitat_id'));

        $this->hasMany('MaintenanceDeposit as MaintenanceDeposits', array(
             'local' => 'id',
             'foreign' => 'habitat_id'));

        $this->hasMany('ExternalStrain as ExternalStrains', array(
             'local' => 'id',
             'foreign' => 'habitat_id'));

        $this->hasMany('Isolation as Isolations', array(
             'local' => 'id',
             'foreign' => 'habitat_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}