<?php

/**
 * BaseGlossaryTerm
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $term
 * @property string $synonyms
 * 
 * @method integer      getId()       Returns the current record's "id" value
 * @method string       getTerm()     Returns the current record's "term" value
 * @method string       getSynonyms() Returns the current record's "synonyms" value
 * @method GlossaryTerm setId()       Sets the current record's "id" value
 * @method GlossaryTerm setTerm()     Sets the current record's "term" value
 * @method GlossaryTerm setSynonyms() Sets the current record's "synonyms" value
 * 
 * @package    bna_green_house
 * @subpackage model
 * @author     Eliezer Talon <elitalon@inventiaplus.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGlossaryTerm extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('glossary_term');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('term', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('synonyms', 'string', null, array(
             'type' => 'string',
             ));


        $this->index('glossary_term', array(
             'fields' => 
             array(
              0 => 'term',
             ),
             ));
        $this->option('type', 'INNODB');
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}