<?php

/**
 * BaseMaintenanceDepositRelative
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property integer $maintenance_deposit_id
 * @property MaintenanceDeposit $MaintenanceDeposit
 * 
 * @method integer                    getId()                     Returns the current record's "id" value
 * @method string                     getName()                   Returns the current record's "name" value
 * @method integer                    getMaintenanceDepositId()   Returns the current record's "maintenance_deposit_id" value
 * @method MaintenanceDeposit         getMaintenanceDeposit()     Returns the current record's "MaintenanceDeposit" value
 * @method MaintenanceDepositRelative setId()                     Sets the current record's "id" value
 * @method MaintenanceDepositRelative setName()                   Sets the current record's "name" value
 * @method MaintenanceDepositRelative setMaintenanceDepositId()   Sets the current record's "maintenance_deposit_id" value
 * @method MaintenanceDepositRelative setMaintenanceDeposit()     Sets the current record's "MaintenanceDeposit" value
 * 
 * @package    bna_green_house
 * @subpackage model
 * @author     Eliezer Talon <elitalon@inventiaplus.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMaintenanceDepositRelative extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('maintenance_deposit_relative');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('maintenance_deposit_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));

        $this->option('type', 'INNODB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('MaintenanceDeposit', array(
             'local' => 'maintenance_deposit_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}