<?php

/**
 * BaseDnaPrimer
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property enum $direction
 * @property string $orientation
 * @property Doctrine_Collection $Pcr
 * @property Doctrine_Collection $Reaction
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method string              getName()        Returns the current record's "name" value
 * @method enum                getDirection()   Returns the current record's "direction" value
 * @method string              getOrientation() Returns the current record's "orientation" value
 * @method Doctrine_Collection getPcr()         Returns the current record's "Pcr" collection
 * @method Doctrine_Collection getReaction()    Returns the current record's "Reaction" collection
 * @method DnaPrimer           setId()          Sets the current record's "id" value
 * @method DnaPrimer           setName()        Sets the current record's "name" value
 * @method DnaPrimer           setDirection()   Sets the current record's "direction" value
 * @method DnaPrimer           setOrientation() Sets the current record's "orientation" value
 * @method DnaPrimer           setPcr()         Sets the current record's "Pcr" collection
 * @method DnaPrimer           setReaction()    Sets the current record's "Reaction" collection
 * 
 * @package    bna_green_house
 * @subpackage model
 * @author     Eliezer Talon <elitalon@inventiaplus.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDnaPrimer extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('dna_primer');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 10, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 10,
             ));
        $this->hasColumn('direction', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'forward',
              1 => 'reverse',
             ),
             ));
        $this->hasColumn('orientation', 'string', 127, array(
             'type' => 'string',
             'length' => 127,
             ));

        $this->option('type', 'INNODB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Pcr', array(
             'local' => 'id',
             'foreign' => 'forward_dna_primer_id'));

        $this->hasMany('PcrReaction as Reaction', array(
             'local' => 'id',
             'foreign' => 'dna_primer_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}