cryopreservation_method:
  class: sfDoctrineRouteCollection
  options:
    model:                CryopreservationMethod
    module:               cryopreservation_method
    prefix_path:          /admin/cryopreservation_method
    column:               id
    with_wildcard_routes: true

identifier:
  class: sfDoctrineRouteCollection
  options:
    model:                Identifier
    module:               identifier
    prefix_path:          /admin/identifier
    column:               id
    with_wildcard_routes: true

depositor:
  class: sfDoctrineRouteCollection
  options:
    model:                Depositor
    module:               depositor
    prefix_path:          /admin/depositor
    column:               id
    with_wildcard_routes: true

isolator:
  class: sfDoctrineRouteCollection
  options:
    model:                Isolator
    module:               isolator
    prefix_path:          /admin/isolator
    column:               id
    with_wildcard_routes: true

collector:
  class: sfDoctrineRouteCollection
  options:
    model:                Collector
    module:               collector
    prefix_path:          /admin/collector
    column:               id
    with_wildcard_routes: true

island:
  class: sfDoctrineRouteCollection
  options:
    model:                Island
    module:               island
    prefix_path:          /admin/island
    column:               id
    with_wildcard_routes: true

region:
  class: sfDoctrineRouteCollection
  options:
    model:                Region
    module:               region
    prefix_path:          /admin/region
    column:               id
    with_wildcard_routes: true

country:
  class: sfDoctrineRouteCollection
  options:
    model:                Country
    module:               country
    prefix_path:          /admin/country
    column:               id
    with_wildcard_routes: true

environment:
  class: sfDoctrineRouteCollection
  options:
    model:                Environment
    module:               environment
    prefix_path:          /admin/environment
    column:               id
    with_wildcard_routes: true

habitat:
  class: sfDoctrineRouteCollection
  options:
    model:                Habitat
    module:               habitat
    prefix_path:          /admin/habitat
    column:               id
    with_wildcard_routes: true

radiation:
  class: sfDoctrineRouteCollection
  options:
    model:                Radiation
    module:               radiation
    prefix_path:          /admin/radiation
    column:               id
    with_wildcard_routes: true

taxonomic_class:
  class: sfDoctrineRouteCollection
  options:
    model:                TaxonomicClass
    module:               taxonomic_class
    prefix_path:          /admin/taxonomic_class
    column:               id
    with_wildcard_routes: true

genus:
  class: sfDoctrineRouteCollection
  options:
    model:                Genus
    module:               genus
    prefix_path:          /admin/genus
    column:               id
    with_wildcard_routes: true

species:
  class: sfDoctrineRouteCollection
  options:
    model:                Species
    module:               species
    prefix_path:          /admin/species
    column:               id
    with_wildcard_routes: true

authority:
  class: sfDoctrineRouteCollection
  options:
    model:                Authority
    module:               authority
    prefix_path:          /admin/authority
    column:               id
    with_wildcard_routes: true

sf_guard_user:
  class: sfDoctrineRouteCollection
  options:
    model:                sfGuardUser
    module:               sfGuardUser
    prefix_path:          /admin/user
    column:               id
    with_wildcard_routes: true

sf_guard_group:
  class: sfDoctrineRouteCollection
  options:
    model:                sfGuardGroup
    module:               sfGuardGroup
    prefix_path:          /admin/role
    column:               id
    with_wildcard_routes: true

sf_guard_permission:
  class: sfDoctrineRouteCollection
  options:
    model:                sfGuardPermission
    module:               sfGuardPermission
    prefix_path:          /admin/permission
    column:               id
    with_wildcard_routes: true

login:
  url:   /admin/login
  param: { module: sfGuardAuth, action: signin }

logout:
  url:   /admin/logout
  param: { module: sfGuardAuth, action: signout }

homepage:
  url:    /admin
  param:  { module: radiation, action: index }

