default:
  http_metas:
    content-type: text/html

  metas:
    title:        Algae culture management | Banco Español de Algas
    description:  Algae culture management of Banco Español de Algas
    keywords:     algae, bna, bea, banco, nacional, algas, español, marine, biotechnology, strains, culture
    language:     en
    robots:       index, follow
  
  stylesheets:    [main.css]

  javascripts:    []

  has_layout:     true
  layout:         layout
