<?php

/**
 * Collector
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    bna_green_house
 * @subpackage model
 * @author     Eliezer Talon <elitalon@inventiaplus.com>
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class Collector extends BaseCollector {
	
	public function __toString() {
		return $this->getName().' '.$this->getSurname();
	}
	
	public function getNbSamples() {
		return Doctrine_Query::create()
			->from('SampleCollectors s')
			->where('s.collector_id = ?', $this->getId())
			->count();
	}
	
	public function getNbPatentDeposits() {
		return Doctrine_Query::create()
			->from('PatentDepositCollectors s')
			->where('s.collector_id = ?', $this->getId())
			->count();
	}
	
	public function getNbMaintenanceDeposits() {
		return Doctrine_Query::create()
			->from('MaintenanceDepositCollectors s')
			->where('s.collector_id = ?', $this->getId())
			->count();
	}

}
