<?php

/**
 * Container
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    bna_green_house
 * @subpackage model
 * @author     Eliezer Talon <elitalon@inventiaplus.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Container extends BaseContainer {
	public function getNbStrains() {
		return Doctrine_Query::create()
			->from('StrainContainers s')
			->where('s.container_id = ?', $this->getId())
			->count();
	}
}
