<?php

/**
 * CryopreservationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CryopreservationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CryopreservationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Cryopreservation');
    }
}