<?php

/**
 * DepositorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DepositorTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DepositorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Depositor');
    }
}