<?php

/**
* DnaExtractionTable
* 
* This class has been auto-generated by the Doctrine ORM Framework
*/
class DnaExtractionTable extends Doctrine_Table {
	/**
	* Returns an instance of this class.
	*
	* @return object DnaExtractionTable
	*/
	public static function getInstance() {
		return Doctrine_Core::getTable('DnaExtraction');
	}
	
	public function findByTerm($term = '') {
		if ( preg_match('/^(BEA)?0*([1-9]\d*)/', $term, $matches) ) {
			return $this->createQuery('s')
				->leftJoin('s.Strain st')
				->where('st.id LIKE ?', $matches[2])
				->execute();
		}
		else {
			return $this->createQuery('s')->execute();
		}
	}
	
}