<?php

/**
* DnaPrimerTable
* 
* This class has been auto-generated by the Doctrine ORM Framework
*/
class DnaPrimerTable extends Doctrine_Table {
	/**
	* Returns an instance of this class.
	*
	* @return object DnaPrimerTable
	*/
	public static function getInstance() {
		return Doctrine_Core::getTable('DnaPrimer');
	}
	
	/**
	 * Returns a query that select forward DNA primers
	 *
	 * @return object DoctrineCollection
	 * @author Eliezer Talon
	 * @version 2011-07-11
	*/
	public function findForwardPrimersQuery() {
		return $this->createQuery('dna')
			->where('dna.direction = ?', sfConfig::get('app_forward_dna_primer_direction'));
		return $query;
	}
	
	/**
	 * Returns a query that select reverse DNA primers
	 *
	 * @return object DoctrineCollection
	 * @author Eliezer Talon
	 * @version 2011-07-11
	*/
	public function findReversePrimersQuery() {
		return $this->createQuery('dna')
			->where('dna.direction = ?', sfConfig::get('app_reverse_dna_primer_direction'));
		return $query;
	}
}