<?php

/**
 * DnaPrimerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DnaPrimerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DnaPrimerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DnaPrimer');
    }
}