<?php

/**
 * DnaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DnaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DnaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Dna');
    }
}