<?php

/**
 * Environment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    bna_green_house
 * @subpackage model
 * @author     Eliezer Talon <elitalon@inventiaplus.com>
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class Environment extends BaseEnvironment {
	public function getNbSamples() {
		return Doctrine_Query::create()
			->from('Sample s')
			->where('s.environment_id = ?', $this->getId())
			->count();
	}
}
