<?php

/**
 * ExternalStrainRelativeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ExternalStrainRelativeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ExternalStrainRelativeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ExternalStrainRelative');
    }
}