<?php
/**
 * Model class
 *
 * acm : Algae Culture Management (https://github.com/singularfactory/ACM)
 * Copyright 2012, Singular Factory <info@singularfactory.com>
 *
 * This file is part of ACM
 *
 * ACM is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * ACM is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with ACM.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @copyright     Copyright 2012, Singular Factory <info@singularfactory.com>
 * @package       ACM.Lib.Model
 * @since         1.0
 * @link          https://github.com/singularfactory/ACM
 * @license       GPLv3 License (http://www.gnu.org/licenses/gpl.txt)
 */

/**
 * IslandTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IslandTable extends Doctrine_Table {
	/**
	* Returns an instance of this class.
	*
	* @return object IslandTable
	*/
	public static function getInstance() {
		return Doctrine_Core::getTable('Island');
	}

	/**
	 * Returns the ID of the default island to show in selects
	 *
	 * @param	string	$regionId
	 * @return	integer
	 *
 * @since 1.0	 */
	public function getDefaultIslandId($regionId) {
		$island = $this->createQuery()
			->from('Island i')
			->where('i.name LIKE ?', '%'.sfConfig::get('app_default_island_name').'%')
			->fetchOne();

		if ( $island ) {
			return $island->getId();
		}

		return null;
	}

	/**
	 * Returns a query that select islands of a region
	 *
	 * @param string $regionId
	 * @return object DoctrineRecord
	 */
	public function getIslandsQuery($regionId = null) {
		$query = $this->createQuery('i');
		if ( $regionId ) {
			$query->where('i.region_id = ?', $regionId);
		}
		return $query;
	}

	/**
	 * Returns a list of islands, optionally filter by region
	 *
	 * @param integer $regionId Id of a region
	 * @return object DoctrineRecord
	 */
	public function getIslands($regionId = null) {
		return $this->getIslandsQuery($regionId)->execute();
	}

}