<?php

/**
* Isolation
*
* This class has been auto-generated by the Doctrine ORM Framework
*
* @package    bna_green_house
* @subpackage model
* @author     Eliezer Talon <elitalon@inventiaplus.com>
* @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
*/
class Isolation extends BaseIsolation {

	public function getCode() {
		if ( $code = $this->getExternalCode() ) {
			return $code;
		}
		else if ( $sample = $this->getSample() ) {
			return $sample->getCode();
		}
		else if ( $strain = $this->getStrain() ) {
			return $strain->getFullCode();
		}
		elseif ($externalStrain = $this->getExternalStrain()) {
			return $externalStrain->getFullCode();
		}
	}

	public function getReceptionDate() {
		if ( $date = $this->_get('reception_date') ) {
			return $this->formatDate($date);
		}
		else {
			return sfConfig::get('app_no_data_message');
		}
	}

	public function getDeliveryDate() {
		if ( $date = $this->_get('delivery_date') ) {
			return $this->formatDate($date);
		}
		else {
			return sfConfig::get('app_no_data_message');
		}
	}

	public function getFormattedTaxonomicClass() {
		if ( $object = $this->getTaxonomicClass() ) {
			if ( $object->exists() ) {
				return $object->getName();
			}
		}

		return sfConfig::get('app_no_data_message');
	}

	public function getFormattedGenus() {
		if ( $object = $this->getGenus() ) {
			if ( $object->exists() ) {
				return $object->getName();
			}
		}

		return sfConfig::get('app_no_data_message');
	}

	public function getFormattedSpecies() {
		if ( $object = $this->getSpecies() ) {
			if ( $object->exists() ) {
				return $object->getName();
			}
		}

		return sfConfig::get('app_no_data_message');
	}

	public function getFormattedAuthority() {
		if ( $object = $this->getAuthority() ) {
			if ( $object->exists() ) {
				return $object->getName();
			}
		}

		return sfConfig::get('app_no_data_message');
	}

	public function getFormattedLocation() {
		if ( $object = $this->getLocation() ) {
			if ( $object->exists() ) {
				return $object->getName();
			}
		}

		return sfConfig::get('app_no_data_message');
	}

	public function getFormattedEnvironment() {
		if ( $object = $this->getEnvironment() ) {
			if ( $object->exists() ) {
				return $object->getName();
			}
		}

		return sfConfig::get('app_no_data_message');
	}

	public function getFormattedHabitat() {
		if ( $object = $this->getHabitat() ) {
			if ( $object->exists() ) {
				return $object->getName();
			}
		}

		return sfConfig::get('app_no_data_message');
	}

	public function getTaxonomicName() {
		return sprintf('%s %s %s', $this->getFormattedTaxonomicClass(), $this->getFormattedGenus(), $this->getFormattedSpecies());
	}

	public function getGenusAndSpecies() {
		return sprintf('%s %s', $this->getFormattedGenus(), $this->getSpecies());
	}

}
