<?php

/**
 * KingdomTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class KingdomTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object KingdomTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Kingdom');
    }
}