<?php

/**
 * LocationCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LocationCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LocationCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LocationCategory');
    }
}