<?php

/**
 * MaintenanceDepositCollectorsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MaintenanceDepositCollectorsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MaintenanceDepositCollectorsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MaintenanceDepositCollectors');
    }
}