<?php

/**
 * MicroscopicPictureTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MicroscopicPictureTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MicroscopicPictureTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MicroscopicPicture');
    }
}