<?php

/**
 * PatentDepositMaintenanceStatusTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PatentDepositMaintenanceStatusTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PatentDepositMaintenanceStatusTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PatentDepositMaintenanceStatus');
    }
}