<?php

/**
 * PatentDepositTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PatentDepositTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PatentDepositTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PatentDeposit');
    }
}