<?php

/**
 * PatentDepositCollectorsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PatentDepositCollectorsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PatentDepositCollectorsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PatentDepositCollectors');
    }
}