<?php

/**
 * PcrReactionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PcrReactionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PcrReactionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PcrReaction');
    }
}