<?php

/**
 * PetitionersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PetitionersTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PetitionersTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Petitioners');
    }
}