<?php

/**
 * PhylumTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PhylumTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PhylumTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Phylum');
    }
}