<?php

/**
* Project
* 
* This class has been auto-generated by the Doctrine ORM Framework
* 
* @package    bna_green_house
* @subpackage model
* @author     Eliezer Talon <elitalon@inventiaplus.com>
* @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
*/
class Project extends BaseProject {
	
	public function getCode() {
		if ( $sample = $this->getSample() ) {
			return $sample->getCode();
		}
		else if ( $strain = $this->getStrain() ) {
			return $strain->getFullCode();
		}
		
		return sfConfig::get('app_no_data_message');
	}
	
	public function getInoculationDate() {
		if ( $date = $this->_get('inoculation_date') ) {
			return $this->formatDate($date);
		}
		else {
			return sfConfig::get('app_no_data_message');
		}
	}
	
	public function getDeliveryDate() {
		if ( $date = $this->_get('delivery_date') ) {
			return $this->formatDate($date);
		}
		else {
			return sfConfig::get('app_no_data_message');
		}
	}
	
	public function getFormattedAmount() {
		return sprintf('%.2f %s', $this->_get('amount'), sfConfig::get('app_project_amount_unit'));
	}
	
}
