<?php
/**
* RegionTable
* 
* This class has been auto-generated by the Doctrine ORM Framework
*/
class RegionTable extends Doctrine_Table {
	/**
	* Returns an instance of this class.
	*
	* @return object RegionTable
	*/
	public static function getInstance() {
		return Doctrine_Core::getTable('Region');
	}
	
	/**
	 * Returns the ID of the default region to show in selects
	 *
	 * @param	string	$countryId
	 * @return	integer
	 * 
	 * @author	Eliezer Talon
	 * @version	2011-04-13
	 */
	public function getDefaultRegionId($countryId) {
		$region = $this->createQuery()
			->from('Region r')
			->where('r.name LIKE ?', '%'.sfConfig::get('app_default_region_name').'%')
			->fetchOne();
		
		return $region->getId();
	}
	
	/**
	 * Returns a query that select regions of a country
	 *
	 * @param string $countryId 
	 * @return object DoctrineRecord
	 * @author Eliezer Talon
	 */
	public function getRegionsQuery($countryId = null) {
		$query = $this->createQuery('r');
		if ( $countryId ) {
			$query->where('r.country_id = ?', $countryId);
		}
		return $query;
	}
	
	/**
	 * Returns a list of regions, optionally filter by country
	 *
	 * @param integer $countryId Id of a country
	 * @return object DoctrineRecord
	 * @author Eliezer Talon
	 */
	public function getRegions($countryId = null) {
		return $this->getRegionsQuery($countryId)->execute();
	}
	
}