<?php

/**
* SampleCollectorsTable
* 
* This class has been auto-generated by the Doctrine ORM Framework
*/
class SampleCollectorsTable extends Doctrine_Table {
	/**
	* Returns an instance of this class.
	*
	* @return object SampleCollectorsTable
	*/
	public static function getInstance() {
		return Doctrine_Core::getTable('SampleCollectors');
	}
}