<?php

/**
 * StrainIsolatorsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StrainIsolatorsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object StrainIsolatorsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('StrainIsolators');
    }
}