<?php

/**
 * StrainUsageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StrainUsageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object StrainUsageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('StrainUsage');
    }
}