<?php

/**
 * StrainTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StrainTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object StrainTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Strain');
    }
}