<?php

/**
 * SubkingdomTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SubkingdomTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SubkingdomTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Subkingdom');
    }
}