<?php

/**
 * UsageAreaUsagesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UsageAreaUsagesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UsageAreaUsagesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UsageAreaUsages');
    }
}