default:
  http_metas:
    content-type: text/html

  metas:
    title:        Banco Español de Algas | Green House
    description:  Algae cultures management of Banco Español de Algas
    keywords:     algae, bna, bea, banco, nacional, algas, español, marine, biotechnology, strains, culture
    language:     en
    robots:       index, follow

  stylesheets:    [login.css]

  javascripts:    []

  has_layout:     true
  layout:         login
