# Routes for Sample module
sample:
  class:   sfDoctrineRouteCollection
  options: { model: Sample }

# Routes for Location model
location:
  class:   sfDoctrineRouteCollection
  options: { model: Location }

# Routes for Country module
country:
  class:   sfDoctrineRouteCollection
  options: { model: Country }

# Routes for Region module
region:
  class:   sfDoctrineRouteCollection
  options: { model: Region }

# Routes for Island module
island:
  class:   sfDoctrineRouteCollection
  options: { model: Island }

# Routes for Habitat module
habitat:
  class:   sfDoctrineRouteCollection
  options: { model: Habitat }

# Routes for Environment module
environment:
  class:   sfDoctrineRouteCollection
  options: { model: Environment }

# Routes for Radiation module
radiation:
  class:   sfDoctrineRouteCollection
  options: { model: Radiation }

# Routes for Collector module
collector:
  class:   sfDoctrineRouteCollection
  options: { model: Collector }



# Default rules (catch all)
homepage:
  url:    /
  param:  { module: sample, action: index }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*