sample:
  class:   sfDoctrineRouteCollection
  options: { model: Sample }

ecosystem:
  class:   sfDoctrineRouteCollection
  options: { model: Ecosystem }

country:
  class:   sfDoctrineRouteCollection
  options: { model: Country }

province:
  class:   sfDoctrineRouteCollection
  options: { model: Province }

user:
  class:  /
  param:  { module: sample, action: index }

settings:
  url:    /settings
  param:  { module: country, action: index }

search:
  url:    /
  param:  { module: sample, action: index }

homepage:
  url:    /
  param:  { module: sample, action: index }