location:
  class:   sfDoctrineRouteCollection
  options: { model: Location }

location_search:
  url:          location/search/:criteria
  param:        { module: location, action: index }
  requirements: { criteria: .* }  # Search pattern is optional, by default all results are shown

sample:
  class:   sfDoctrineRouteCollection
  options: { model: Sample }

sample_search:
  url:          sample/search/:criteria
  param:        { module: sample, action: index }
  requirements: { criteria: .* }  # Search pattern is optional, by default all results are shown

sample_location:
  url:    sample/location/:id
  param:  { module: sample, action: location }
  
profile:
  class:   sfDoctrineRouteCollection
  options: { model: sfGuardUser }

login:
  url:   /login
  param: { module: sfGuardAuth, action: signin }

logout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }

# Default rules (catch all)
homepage:
  url:    /
  param:  { module: sample, action: index }