###
# Country model related routes
###
country_find_regions:
  url:    country/findRegions/:country
  param:  { module: country, action: findRegions }
  requirements: { country: .* } # Search pattern is optional, by default all results are shown


###
# Region model related routes
###
region_find_islands:
  url:    region/findIslands/:region
  param:  { module: region, action: findIslands }
  requirements: { region: .* } # Search pattern is optional, by default all results are shown


###
# Location model related routes
###
location:
  class:   sfDoctrineRouteCollection
  options: { model: Location }

location_search:
  url:          location/search/:criteria
  param:        { module: location, action: index }
  requirements: { criteria: .* }  # Search pattern is optional, by default all results are shown

location_pagination:
  url:          location/page/:page
  param:        { module: location, action: index }
  requirements: { page: .* }


###
# Sample model related routes
###
sample:
  class:   sfDoctrineRouteCollection
  options: { model: Sample }

sample_search:
  url:          sample/search/:criteria
  param:        { module: sample, action: index }
  requirements: { criteria: .* }  # Search pattern is optional, by default all results are shown

sample_find_locations:
  url:    sample/findLocations/:term
  param:  { module: sample, action: findLocations }
  requirements: { term: .* }  # Search pattern is optional, by default all results are shown

sample_pagination:
  url:          sample/page/:page
  param:        { module: sample, action: index }
  requirements: { page: \d* }


###
# Strain model related routes
###
strain:
  class:   sfDoctrineRouteCollection
  options: { model: Strain }

strain_search:
  url:          strain/search/:criteria
  param:        { module: strain, action: index }
  requirements: { criteria: .* }  # Search pattern is optional, by default all results are shown

strain_find_samples:
  url:    strain/findSamples/:term
  param:  { module: strain, action: findSamples }
  requirements: { term: .* }  # Search pattern is optional, by default all results are shown

strain_pagination:
  url:          strain/page/:page
  param:        { module: strain, action: index }
  requirements: { page: \d* }


###
# GrowthMedium model related routes
###
growth_medium:
  class:   sfDoctrineRouteCollection
  options: { model: GrowthMedium }

growth_medium_search:
  url:          growth_medium/search/:criteria
  param:        { module: growth_medium, action: index }
  requirements: { criteria: .* }  # Search pattern is optional, by default all results are shown

growth_medium_pagination:
  url:          growth_medium/page/:page
  param:        { module: growth_medium, action: index }
  requirements: { page: \d* }


###
# sfGuardUser model related routes
###
profile:
  class:   sfDoctrineRouteCollection
  options: { model: sfGuardUser }

login:
  url:   /login
  param: { module: sfGuardAuth, action: signin }

logout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }


###
# Default rules
###
homepage:
  url:    /
  param:  { module: sample, action: index }