###
# Country model related routes
###
country_find_regions:
  url:    country/findRegions/:country
  param:  { module: country, action: findRegions }
  requirements: { country: .* } # Search pattern is optional, by default all results are shown


###
# Region model related routes
###
region_find_islands:
  url:    region/findIslands/:region
  param:  { module: region, action: findIslands }
  requirements: { region: .* } # Search pattern is optional, by default all results are shown


###
# Location model related routes
###
location:
  class:   sfDoctrineRouteCollection
  options: { model: Location }

location_search:
  url:          location/search/:criteria
  param:        { module: location, action: index }
  requirements: { criteria: "[^/]*" }  # Search pattern is optional, by default all results are shown

location_pagination:
  url:          location/page/:page
  param:        { module: location, action: index, page: 1 }
  requirements: { page: \d+ }

location_search_pagination:
  url:          location/search/:criteria/page/:page
  param:        { module: location, action: index, page: 1 }
  requirements: { criteria: "[^/]+", page: \d+ }


###
# Sample model related routes
###
sample:
  class:   sfDoctrineRouteCollection
  options: { model: Sample }

sample_search:
  url:          sample/search/:criteria
  param:        { module: sample, action: index }
  requirements: { criteria: "[^/]*" }  # Search pattern is optional, by default all results are shown

sample_find_locations:
  url:    sample/findLocations/:term
  param:  { module: sample, action: findLocations }
  requirements: { term: .* }  # Search pattern is optional, by default all results are shown

sample_pagination:
  url:          sample/page/:page
  param:        { module: sample, action: index, page: 1 }
  requirements: { page: \d+ }

sample_search_pagination:
  url:          sample/search/:criteria/page/:page
  param:        { module: sample, action: index, page: 1 }
  requirements: { criteria: "[^/]+", page: \d+ }


###
# Strain model related routes
###
strain:
  class:   sfDoctrineRouteCollection
  options: { model: Strain }

strain_search:
  url:          strain/search/:criteria
  param:        { module: strain, action: index }
  requirements: { criteria: "[^/]*" }  # Search pattern is optional, by default all results are shown

strain_find_samples:
  url:    strain/findSamples/:term
  param:  { module: strain, action: findSamples }
  requirements: { term: .* }  # Search pattern is optional, by default all results are shown

strain_pagination:
  url:          strain/page/:page
  param:        { module: strain, action: index, page: 1 }
  requirements: { page: \d+ }

strain_search_pagination:
  url:          strain/search/:criteria/page/:page
  param:        { module: strain, action: index, page: 1 }
  requirements: { criteria: "[^/]+", page: \d+ }

strain_new_related_model_form:
  url:          strain/new_related_model/:related_model
  param:        { module: strain, action: newRelatedModelEmbeddedForm }
  requirements: { sf_method: get, related_model: "[^/]+" }


###
# CultureMedium model related routes
###
culture_medium:
  class:   sfDoctrineRouteCollection
  options: { model: CultureMedium }

culture_medium_search:
  url:          culture_medium/search/:criteria
  param:        { module: culture_medium, action: index }
  requirements: { criteria: "[^/]*" }  # Search pattern is optional, by default all results are shown

culture_medium_pagination:
  url:          culture_medium/page/:page
  param:        { module: culture_medium, action: index, page: 1 }
  requirements: { page: \d+ }

culture_medium_search_pagination:
  url:          culture_medium/search/:criteria/page/:page
  param:        { module: culture_medium, action: index, page: 1 }
  requirements: { criteria: "[^/]+", page: \d+ }


###
# DnaExtraction model related routes
###
dna_extraction:
  class:   sfDoctrineRouteCollection
  options: { model: DnaExtraction }

dna_extraction_search:
  url:          dna_extraction/search/:criteria
  param:        { module: dna_extraction, action: index }
  requirements: { criteria: "[^/]*" }  # Search pattern is optional, by default all results are shown

dna_extraction_find_strains:
  url:          dna_extraction/findStrains/:term
  param:        { module: dna_extraction, action: findStrains }
  requirements: { term: .* }  # Search pattern is optional, by default all results are shown

dna_extraction_pagination:
  url:          dna_extraction/page/:page
  param:        { module: dna_extraction, action: index, page: 1 }
  requirements: { page: \d+ }

dna_extraction_search_pagination:
  url:          dna_extraction/search/:criteria/page/:page
  param:        { module: dna_extraction, action: index, page: 1 }
  requirements: { criteria: "[^/]+", page: \d+ }


###
# Pcr model related routes
###
pcr:
  class:   sfDoctrineRouteCollection
  options: { model: Pcr, actions: [create, edit, update, delete, show] }

pcr_new:
  url:          /pcr/new/:dna_extraction
  class:        sfDoctrineRoute
  param:        { module: pcr, action: new }
  requirements: { sf_method: [get, head] }
  options:      { model: Pcr, type: object }

pcr_create:
  url:          /pcr/:dna_extraction
  class:        sfDoctrineRoute
  param:        { module: pcr, action: create }
  requirements: { sf_method: post, dna_extraction: "\d+" }
  options:      { model: Pcr, type: object }


###
# PcrGel model related routes
###
pcr_gel:
  class:   sfDoctrineRouteCollection
  options: { model: PcrGel, actions: [edit, update, delete] }


###
# DnaSequence model related routes
###
dna_sequence:
  class:   sfDoctrineRouteCollection
  options: { model: DnaSequence, actions: [create, edit, update, delete, show] }

dna_sequence_new:
  url:          /dna_sequence/new/:pcr
  class:        sfDoctrineRoute
  param:        { module: dna_sequence, action: new }
  requirements: { sf_method: [get, head] }
  options:      { model: DnaSequence, type: object }


###
# PcrReaction model related routes
###
pcr_reaction:
  class:   sfDoctrineRouteCollection
  options: { model: PcrReaction, actions: [edit, update, delete] }


###
# sfGuardUser model related routes
###
profile:
  class:      sfDoctrineRouteCollection
  options:
    model:    sfGuardUser
    actions:  [edit, update]

profile_shortcut:
  class:        sfDoctrineRoute
  options:      { model: sfGuardUser, type: object }
  url:          /profile/:id
  param:        { module: profile, action: edit }
  requirements: { id: '[0-9]+' }

profile_token_regeneration:
  class:    sfDoctrineRoute
  options:  { model: sfGuardUser, type: object }
  url:      /profile/new_token
  param:    { module: profile, action: newToken }

login:
  url:   /login
  param: { module: sfGuardAuth, action: signin }

logout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }

upload_progress:
  url:    /:module/uploadProgress/:id
  param:  { action: uploadProgress }


###
# Inbox routes
###
inbox:
  class:   sfDoctrineRouteCollection
  options: { model: Notification, actions: [list, show, delete] }

inbox_search:
  url:          inbox/search/:criteria
  param:        { module: inbox, action: index }
  requirements: { criteria: "[^/]*" }  # Search pattern is optional, by default all results are shown

inbox_pagination:
  url:          inbox/page/:page
  param:        { module: inbox, action: index, page: 1 }
  requirements: { page: \d+ }

inbox_search_pagination:
  url:          inbox/search/:criteria/page/:page
  param:        { module: inbox, action: index, page: 1 }
  requirements: { criteria: "[^/]+", page: \d+ }


###
# Purchase order routes
###
purchase_order:
  class:   sfDoctrineRouteCollection
  options: { model: PurchaseOrder, actions: [list, show, edit, update, delete] }

purchase_order_search:
  url:          purchase_order/search/:criteria
  param:        { module: purchase_order, action: index }
  requirements: { criteria: "[^/]*" }  # Search pattern is optional, by default all results are shown

purchase_order_pagination:
  url:          purchase_order/page/:page
  param:        { module: purchase_order, action: index, page: 1 }
  requirements: { page: \d+ }

purchase_order_search_pagination:
  url:          purchase_order/search/:criteria/page/:page
  param:        { module: purchase_order, action: index, page: 1 }
  requirements: { criteria: "[^/]+", page: \d+ }


###
# Purchase item routes
###
purchase_item:
  class:   sfDoctrineRouteCollection
  options: { model: PurchaseItem, actions: [edit, update] }


###
# Project model related routes
###
project:
  class:   sfDoctrineRouteCollection
  options: { model: Project }

project_search:
  url:          project/search/:criteria
  param:        { module: project, action: index }
  requirements: { criteria: "[^/]*" }  # Search pattern is optional, by default all results are shown

project_find_strains:
  url:          project/findStrains/:term
  param:        { module: project, action: findStrains }
  requirements: { term: .* }  # Search pattern is optional, by default all results are shown

project_pagination:
  url:          project/page/:page
  param:        { module: project, action: index, page: 1 }
  requirements: { page: \d+ }

project_search_pagination:
  url:          project/search/:criteria/page/:page
  param:        { module: project, action: index, page: 1 }
  requirements: { criteria: "[^/]+", page: \d+ }


###
# PatentDeposit model related routes
###
patent_deposit:
  class:   sfDoctrineRouteCollection
  options: { model: PatentDeposit }

patent_deposit_find_locations:
  url:    patent_deposit/findLocations/:term
  param:  { module: patent_deposit, action: findLocations }
  requirements: { term: .* }  # Search pattern is optional, by default all results are shown

patent_deposit_search:
  url:          patent_deposit/search/:criteria
  param:        { module: patent_deposit, action: index }
  requirements: { criteria: "[^/]*" }  # Search pattern is optional, by default all results are shown

patent_deposit_pagination:
  url:          patent_deposit/page/:page
  param:        { module: patent_deposit, action: index, page: 1 }
  requirements: { page: \d+ }

patent_deposit_search_pagination:
  url:          patent_deposit/search/:criteria/page/:page
  param:        { module: patent_deposit, action: index, page: 1 }
  requirements: { criteria: "[^/]+", page: \d+ }


###
# MaintenanceDeposit model related routes
###
maintenance_deposit:
  class:   sfDoctrineRouteCollection
  options: { model: MaintenanceDeposit }

maintenance_deposit_find_locations:
  url:    maintenance_deposit/findLocations/:term
  param:  { module: maintenance_deposit, action: findLocations }
  requirements: { term: .* }  # Search pattern is optional, by default all results are shown

maintenance_deposit_search:
  url:          maintenance_deposit/search/:criteria
  param:        { module: maintenance_deposit, action: index }
  requirements: { criteria: "[^/]*" }  # Search pattern is optional, by default all results are shown

maintenance_deposit_pagination:
  url:          maintenance_deposit/page/:page
  param:        { module: maintenance_deposit, action: index, page: 1 }
  requirements: { page: \d+ }

maintenance_deposit_search_pagination:
  url:          maintenance_deposit/search/:criteria/page/:page
  param:        { module: maintenance_deposit, action: index, page: 1 }
  requirements: { criteria: "[^/]+", page: \d+ }


###
# Isolation model related routes
###
isolation:
  class:   sfDoctrineRouteCollection
  options: { model: Isolation }

isolation_filter_by_subject_new:
  url:          isolation/new/:subject
  param:        { module: isolation, action: new, subject: sample }
  requirements: { subject: "(sample)|(strain)|(external)", sf_method: [get, head] }

isolation_filter_by_subject_edit:
  url:          isolation/:id/edit/:subject
  param:        { module: isolation, action: edit, subject: sample }
  requirements: { subject: "(sample)|(strain)|(external)", id: \d+, sf_method: [get, head] }

isolation_find_locations:
  url:    isolation/findLocations/:term
  param:  { module: isolation, action: findLocations }
  requirements: { term: .* }  # Search pattern is optional, by default all results are shown

isolation_find_samples:
  url:    isolation/findSamples/:term
  param:  { module: isolation, action: findSamples }
  requirements: { term: .* }  # Search pattern is optional, by default all results are shown

isolation_find_strains:
  url:          isolation/findStrains/:term
  param:        { module: isolation, action: findStrains }
  requirements: { term: .* }  # Search pattern is optional, by default all results are shown

isolation_search:
  url:          isolation/search/:criteria
  param:        { module: isolation, action: index }
  requirements: { criteria: "[^/]*" }  # Search pattern is optional, by default all results are shown

isolation_pagination:
  url:          isolation/page/:page
  param:        { module: isolation, action: index, page: 1 }
  requirements: { page: \d+ }

isolation_search_pagination:
  url:          isolation/search/:criteria/page/:page
  param:        { module: isolation, action: index, page: 1 }
  requirements: { criteria: "[^/]+", page: \d+ }


###
# API routes
###
api_sampling_information:
  url:          /api/:token/samplingInformation/:timestamp
  param:        { module: api, action: samplingInformation }
  requirements: { sf_method: get, timestamp: \d+ }

api_add_sampling_information:
  url:          /api/:token/addSamplingInformation
  param:        { module: api, action: addSamplingInformation }
  requirements: { sf_method: post }

api_sync_location_information:
  url:          /api/:token/syncLocationInformation
  param:        { module: api, action: syncLocationInformation }
  requirements: { sf_method: post }

api_new_purchase_order:
  url:          /api/:token/newPurchaseOrder
  param:        { module: api, action: newPurchaseOrder }
  requirements: { sf_method: post }

api_store_catalog:
  url:          /api/:token/storeCatalog
  param:        { module: api, action: storeCatalog }
  requirements: { sf_method: get }


###
# Label module routes
###
label:
  url:          /label
  param:        { module: label, action: configure }
  requirements: { sf_method: [get, head] }


###
# Default rules
###
homepage:
  url:    /
  param:  { module: strain, action: index }

