sample:
  class:   sfDoctrineRouteCollection
  options: { model: Sample }

ecosystem:
  class:   sfDoctrineRouteCollection
  options: { model: Ecosystem }

country:
  class:   sfDoctrineRouteCollection
  options: { model: Country }

province:
  class:   sfDoctrineRouteCollection
  options: { model: Province }

habitat:
  class:   sfDoctrineRouteCollection
  options: { model: Habitat }

environment:
  class:   sfDoctrineRouteCollection
  options: { model: Environment }

settings:
  url:    /settings
  param:  { module: country, action: index }

settings_countries:
  url:    /settings/countries
  param:  { module: country, action: index }

settings_provinces:
  url:    /settings/provinces
  param:  { module: province, action: index }

settings_habitats:
  url:    /settings/habitats
  param:  { module: habitat, action: index }

settings_environments:
  url:    /settings/environments
  param:  { module: environment, action: index }

user:
  url:  /
  param:  { module: sample, action: index }

search:
  url:    /
  param:  { module: sample, action: index }

homepage:
  url:    /
  param:  { module: sample, action: index }