# Routes for Sample module
sample:
  class:   sfDoctrineRouteCollection
  options: { model: Sample }

# Routes for Location model
location:
  class:   sfDoctrineRouteCollection
  options: { model: Location }

# Routes for Country module
country:
  class:   sfDoctrineRouteCollection
  options: { model: Country }

# Routes for Region module
region:
  class:   sfDoctrineRouteCollection
  options: { model: Region }

# Routes for Island module
island:
  class:   sfDoctrineRouteCollection
  options: { model: Island }

# Routes for Habitat module
habitat:
  class:   sfDoctrineRouteCollection
  options: { model: Habitat }

# Routes for Environment module
environment:
  class:   sfDoctrineRouteCollection
  options: { model: Environment }

# Routes for Environment module
radiation:
  class:   sfDoctrineRouteCollection
  options: { model: Radiation }



# Routes for settings module
settings:
  url:    /settings
  param:  { module: country, action: index }

settings_module:
  url:    /settings/:module
  param:  { action: index }

settings_module_action:
  url:    /settings/:module/:action/*


# Routes for authentication
login:
  url:   /login
  param: { module: sfGuardAuth, action: signin }

logout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }

sf_guard_password:
  url:   /request_password
  param: { module: sfGuardAuth, action: password }


# Default rules (catch all)
homepage:
  url:    /
  param:  { module: sample, action: index }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*