sample:
  class:   sfDoctrineRouteCollection
  options: { model: Sample }

ecosystem:
  class:   sfDoctrineRouteCollection
  options: { model: Ecosystem }

homepage:
  url:   /
  param: { module: sample, action: index }