# Routes for Sample module
sample:
  class:   sfDoctrineRouteCollection
  options: { model: Sample }

# Routes for Location model
location:
  class:   sfDoctrineRouteCollection
  options: { model: Location }


# Default rules (catch all)
homepage:
  url:    /
  param:  { module: sample, action: index }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*