sample:
  class:   sfDoctrineRouteCollection
  options: { model: Sample }

ecosystem:
  class:   sfDoctrineRouteCollection
  options: { model: Ecosystem }

user:
  class:   sfDoctrineRouteCollection
  options: { model: User }

settings:
  url:    /settings
  param:  { module: country, action: index }

search:
  url:    /
  param:  { module: sample, action: index }

homepage:
  url:    /
  param:  { module: sample, action: index }