default:
  http_metas:
    content-type: text/html

  metas:
    title:        Algae culture management | Banco Español de Algas
    description:  Algae culture management of Banco Español de Algas
    keywords:     algae, bna, bea, banco, nacional, algas, español, marine, biotechnology, strains, culture
    language:     en
    robots:       index, follow

  stylesheets:    [main.css]

  javascripts:    [jquery.js]

  has_layout:     true
  layout:         layout

indexSuccess:
  stylesheets:  [tables.css]
showSuccess:
  stylesheets:  [tables.css]
editSuccess:
  stylesheets:  [forms.css]
newSuccess:
  stylesheets:  [forms.css]