# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        Banco Español de Algas | Green House
    description:  Algae cultures management of Banco Español de Algas
    keywords:     algae, bna, bea, banco, nacional, algas, español, marine, biotechnology, strains, culture
    language:     en
    robots:       index, follow

  stylesheets:    [main.css, header.css]

  javascripts:    []

  has_layout:     true
  layout:         layout
