configureSuccess:
  stylesheets:  [forms.css, colorbox.css, articles.css]
  javascripts:  ['http://maps.google.com/maps/api/js?sensor=false', jquery-gomap.js, forms.js, colorbox.js, thumbnails.js, articles.js]