generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Identifier
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          identifier
    with_doctrine_route:   true
    actions_base_class:    MyActions
    css:  false

    config:
      actions: ~
      fields: ~
      list:
        title: Identifiers
        display: [name, surname, email, nb_strains, updated_at]
        fields:
          full_name:
            label: Name
          nb_strains:
            label: Strains identified
          updated_at:
            label: Last update
            date_format: f
        sort: ~
      filter:
        display: [name, surname, email]
      form: ~
      edit:
        title: Edit "%%name%% %%surname%%"
      new:
        title: Add a new identifier