generator:
  class: sfDoctrineGenerator
  param:
    model_class:            DnaPrimer
    theme:                  admin
    non_verbose_templates:  true
    with_show:              false
    singular:               ~
    plural:                 ~
    route_prefix:           dna_primer
    with_doctrine_route:    true
    actions_base_class:     MyActions
    css:                    false

    config:
      actions: ~
      fields: ~
      list:
        title: DNA primers
        display: [name, direction, orientation, updated_at]
        fields:
          orientation:
            label: "5' -> 3'"
          updated_at:
            label: Last update
            date_format: f
        sort: ~
      filter:
        display: [name, direction, orientation]
      form: ~
      edit:
        title: Edit "%%name%%"
      new:
        title: Add a new primer