generator:
  class: sfDoctrineGenerator
  param:
    model_class:           ExtractionKit
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          extraction_kit
    with_doctrine_route:   true
    actions_base_class:    MyActions
    css:  false

    config:
      actions: ~
      fields: ~
      list:
        title: DNA extraction kits
        display: [name, updated_at]
        fields:
          updated_at:
            label: Last update
            date_format: f
        sort: ~
      filter:
        display: [name]
      form: ~
      edit:
        title: Edit "%%name%%"
      new:
        title: Add a new extraction kit