dev:
  doctrine:
    class: sfDoctrineDatabase

all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=localhost;dbname=bna_green_house'
      username: bna_green_house
      password: cocoloco
