login:
  url:   /login
  param: { module: sfGuardAuth, action: signin }

logout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }

forgot_password:
  url:   /request_password
  param: { module: sfGuardAuth, action: password }
