<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version3 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('country', 'name', 'string', '255', array(
             'notnull' => '1',
             ));
        $this->changeColumn('ecosystem', 'name', 'string', '255', array(
             'notnull' => '1',
             ));
        $this->changeColumn('ecosystem', 'city', 'string', '255', array(
             'notnull' => '1',
             ));
        $this->changeColumn('ecosystem', 'lanscape_picture', 'string', '255', array(
             ));
        $this->changeColumn('environment', 'name', 'string', '255', array(
             'notnull' => '1',
             ));
        $this->changeColumn('habitat', 'name', 'string', '255', array(
             'notnull' => '1',
             ));
        $this->changeColumn('province', 'name', 'string', '255', array(
             'notnull' => '1',
             ));
        $this->changeColumn('role', 'name', 'string', '255', array(
             'notnull' => '1',
             ));
        $this->changeColumn('sample', 'location', 'string', '255', array(
             'notnull' => '1',
             ));
        $this->changeColumn('sample', 'close_picture', 'string', '512', array(
             ));
        $this->changeColumn('sample', 'laboratory_picture', 'string', '512', array(
             ));
        $this->changeColumn('user', 'username', 'string', '30', array(
             'notnull' => '1',
             ));
        $this->changeColumn('user', 'password', 'string', '30', array(
             'notnull' => '1',
             ));
        $this->changeColumn('user', 'name', 'string', '255', array(
             'notnull' => '1',
             ));
        $this->changeColumn('user', 'surname', 'string', '255', array(
             'notnull' => '1',
             ));
        $this->changeColumn('user', 'email', 'string', '512', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {

    }
}