<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version8 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('ecosystem_picture', 'name');
        $this->addColumn('ecosystem_picture', 'filename', 'string', '255', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->addColumn('ecosystem_picture', 'name', 'string', '255', array(
             'notnull' => '1',
             ));
        $this->removeColumn('ecosystem_picture', 'filename');
    }
}