<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version5 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('ecosystem', 'picture');
        $this->addColumn('ecosystem', 'picture_1', 'string', '255', array(
             ));
        $this->addColumn('ecosystem', 'picture_2', 'string', '255', array(
             ));
        $this->addColumn('ecosystem', 'picture_3', 'string', '255', array(
             ));
        $this->addColumn('ecosystem', 'picture_4', 'string', '255', array(
             ));
        $this->addColumn('ecosystem', 'picture_5', 'string', '255', array(
             ));
    }

    public function down()
    {
        $this->addColumn('ecosystem', 'picture', 'string', '255', array(
             ));
        $this->removeColumn('ecosystem', 'picture_1');
        $this->removeColumn('ecosystem', 'picture_2');
        $this->removeColumn('ecosystem', 'picture_3');
        $this->removeColumn('ecosystem', 'picture_4');
        $this->removeColumn('ecosystem', 'picture_5');
    }
}