<?php
/**
* This class has been auto-generated by the Doctrine ORM Framework
*/
class Version34 extends Doctrine_Migration_Base {
	public function up() {
		$this->dropForeignKey('strain', 'strain_dna_id_dna_id');
		$this->removeIndex('strain', 'strain_dna_id', array('fields' => array(0 => 'dna_id',),));
		$this->removeColumn('strain', 'dna_id');
		
		$this->addColumn('dna', 'strain_id', 'integer', '8', array('notnull' => '1',));
		$this->createForeignKey('dna', 'dna_strain_id_strain_id', array(
			'name' => 'dna_strain_id_strain_id',
			'local' => 'strain_id',
			'foreign' => 'id',
			'foreignTable' => 'strain',
		));
		$this->addIndex('dna', 'dna_strain_id', array('fields' => array(0 => 'strain_id',),));
	}

	public function down() {
		$this->dropForeignKey('dna', 'dna_strain_id_strain_id');
		$this->removeIndex('dna', 'dna_strain_id', array('fields' => array(0 => 'strain_id',),));
		$this->removeColumn('dna', 'strain_id');

		$this->addColumn('strain', 'dna_id', 'integer', '8', array('notnull' => '1',));
		$this->createForeignKey('strain', 'strain_dna_id_dna_id', array(
			'name' => 'strain_dna_id_dna_id',
			'local' => 'dna_id',
			'foreign' => 'id',
			'foreignTable' => 'dna',
		));
		$this->addIndex('strain', 'strain_dna_id', array('fields' => array(0 => 'dna_id',),));
	}
}