<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version32 extends Doctrine_Migration_Base {
    public function up() {
        $this->createForeignKey('detailed_picture', 'detailed_picture_sample_id_sample_id', array(
             'name' => 'detailed_picture_sample_id_sample_id',
             'local' => 'sample_id',
             'foreign' => 'id',
             'foreignTable' => 'sample',
             'onUpdate' => '',
             'onDelete' => 'cascade',
             ));
        $this->createForeignKey('field_picture', 'field_picture_sample_id_sample_id', array(
             'name' => 'field_picture_sample_id_sample_id',
             'local' => 'sample_id',
             'foreign' => 'id',
             'foreignTable' => 'sample',
             'onUpdate' => '',
             'onDelete' => 'cascade',
             ));
        $this->createForeignKey('microscopic_picture', 'microscopic_picture_sample_id_sample_id', array(
             'name' => 'microscopic_picture_sample_id_sample_id',
             'local' => 'sample_id',
             'foreign' => 'id',
             'foreignTable' => 'sample',
             'onUpdate' => '',
             'onDelete' => 'cascade',
             ));
        $this->addIndex('detailed_picture', 'detailed_picture_sample_id', array(
             'fields' => 
             array(
              0 => 'sample_id',
             ),
             ));
        $this->addIndex('field_picture', 'field_picture_sample_id', array(
             'fields' => 
             array(
              0 => 'sample_id',
             ),
             ));
        $this->addIndex('microscopic_picture', 'microscopic_picture_sample_id', array(
             'fields' => 
             array(
              0 => 'sample_id',
             ),
             ));
    }

    public function down() {
        $this->dropForeignKey('detailed_picture', 'detailed_picture_sample_id_sample_id');
        $this->dropForeignKey('field_picture', 'field_picture_sample_id_sample_id');
        $this->dropForeignKey('microscopic_picture', 'microscopic_picture_sample_id_sample_id');
        $this->removeIndex('detailed_picture', 'detailed_picture_sample_id', array(
             'fields' => 
             array(
              0 => 'sample_id',
             ),
             ));
        $this->removeIndex('field_picture', 'field_picture_sample_id', array(
             'fields' => 
             array(
              0 => 'sample_id',
             ),
             ));
        $this->removeIndex('microscopic_picture', 'microscopic_picture_sample_id', array(
             'fields' => 
             array(
              0 => 'sample_id',
             ),
             ));
    }
}