<?php
/**
 * Migration file
 *
 * acm : Algae Culture Management (https://github.com/singularfactory/ACM)
 * Copyright 2012, Singular Factory <info@singularfactory.com>
 *
 * This file is part of ACM
 *
 * ACM is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * ACM is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with ACM.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @copyright     Copyright 2012, Singular Factory <info@singularfactory.com>
 * @package       ACM.Lib.Migration
 * @since         1.0
 * @link          https://github.com/singularfactory/ACM
 * @license       GPLv3 License (http://www.gnu.org/licenses/gpl.txt)
 */

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version29 extends Doctrine_Migration_Base {
	public function up() {
		$this->createTable('authority', array(
			'id' => array('type' => 'integer','primary' => '1','autoincrement' => '1','length' => '8',),
			'name' => array('type' => 'string','notnull' => '1','length' => '255',),
			'created_at' => array('notnull' => '1','type' => 'timestamp','length' => '25',),
			'updated_at' => array('notnull' => '1','type' => 'timestamp','length' => '25',),
			),
			array('type' => 'INNODB','primary' => array(0 => 'id',),
		));

		$this->createTable('taxonomic_class', array(
			'id' => array('type' => 'integer','primary' => '1','autoincrement' => '1','length' => '8',),
			'name' => array('type' => 'string','notnull' => '1','length' => '255',),
			'created_at' => array('notnull' => '1','type' => 'timestamp','length' => '25',),
			'updated_at' => array('notnull' => '1','type' => 'timestamp','length' => '25',),
			),
			array('type' => 'INNODB','primary' => array(0 => 'id',),
		));

		$this->createTable('cryopreservation_method', array(
			'id' => array('type' => 'integer','primary' => '1','autoincrement' => '1','length' => '8',),
			'name' => array('type' => 'string','notnull' => '1','length' => '127',),
			'created_at' => array('notnull' => '1','type' => 'timestamp','length' => '25',),
			'updated_at' => array('notnull' => '1','type' => 'timestamp','length' => '25',),
			),
			array('type' => 'INNODB','primary' => array(0 => 'id',),
		));
		$this->createTable('depositor', array(
			'id' => array('type' => 'integer','primary' => '1','autoincrement' => '1','length' => '8',),
			'name' => array('type' => 'string','notnull' => '1','length' => '127',),
			'surname' => array('type' => 'string','notnull' => '1','length' => '127',),
			'email' => array('type' => 'string','length' => '255',),
			'created_at' => array('notnull' => '1','type' => 'timestamp','length' => '25',),
			'updated_at' => array('notnull' => '1','type' => 'timestamp','length' => '25',),
			),
			array('type' => 'INNODB','primary' => array(0 => 'id',),
		));
		$this->createTable('dna', array(
			'id' => array('type' => 'integer','primary' => '1','autoincrement' => '1','length' => '8',),
			'accession_number' => array('type' => 'string','notnull' => '1','length' => '255',),
			'filename' => array('type' => 'string','notnull' => '1','length' => '255',),
			'created_at' => array('notnull' => '1','type' => 'timestamp','length' => '25',),
			'updated_at' => array('notnull' => '1','type' => 'timestamp','length' => '25',),
			),
			array('type' => 'INNODB','primary' => array(0 => 'id',),
		));
		$this->createTable('genus', array(
			'id' => array('type' => 'integer','primary' => '1','autoincrement' => '1','length' => '8',),
			'name' => array('type' => 'string','notnull' => '1','length' => '255',),
			'created_at' => array('notnull' => '1','type' => 'timestamp','length' => '25',),
			'updated_at' => array('notnull' => '1','type' => 'timestamp','length' => '25',),
			),
			array('type' => 'INNODB','primary' => array(0 => 'id',),
		));
		$this->createTable('growth_medium', array(
			'id' => array('type' => 'integer','primary' => '1','autoincrement' => '1','length' => '8',),
			'name' => array('type' => 'string','notnull' => '1','length' => '255',),
			'description' => array('type' => 'string','notnull' => '1','length' => '',),
			'link' => array('type' => 'string','notnull' => '1','length' => '1024',),
			'created_at' => array('notnull' => '1','type' => 'timestamp','length' => '25',),
			'updated_at' => array('notnull' => '1','type' => 'timestamp','length' => '25',),
			),
			array('type' => 'INNODB','primary' => array(0 => 'id',),
		));
		$this->createTable('identifier', array(
			'id' => array('type' => 'integer','primary' => '1','autoincrement' => '1','length' => '8',),
			'name' => array('type' => 'string','notnull' => '1','length' => '127',),
			'surname' => array('type' => 'string','notnull' => '1','length' => '127',),
			'email' => array('type' => 'string','length' => '255',),
			'created_at' => array('notnull' => '1','type' => 'timestamp','length' => '25',),
			'updated_at' => array('notnull' => '1','type' => 'timestamp','length' => '25',),
			),
			array('type' => 'INNODB','primary' => array(0 => 'id',),
		));
		$this->createTable('isolator', array(
			'id' => array('type' => 'integer','primary' => '1','autoincrement' => '1','length' => '8',),
			'name' => array('type' => 'string','notnull' => '1','length' => '127',),
			'surname' => array('type' => 'string','notnull' => '1','length' => '127',),
			'email' => array('type' => 'string','length' => '255',),
			'created_at' => array('notnull' => '1','type' => 'timestamp','length' => '25',),
			'updated_at' => array('notnull' => '1','type' => 'timestamp','length' => '25',),
			),
			array('type' => 'INNODB','primary' => array(0 => 'id',),
		));
		$this->createTable('maintenance_status', array(
			'id' => array('type' => 'integer','primary' => '1','autoincrement' => '1','length' => '8',),
			'name' => array('type' => 'enum','values' => array(0 => 'Liquid',1 => 'Solid',2 => 'Cryopreserved',),'length' => '',),
			'created_at' => array('notnull' => '1','type' => 'timestamp','length' => '25',),
			'updated_at' => array('notnull' => '1','type' => 'timestamp','length' => '25',),
			),
			array('type' => 'INNODB','primary' => array(0 => 'id',),
		));
		$this->createTable('species', array(
			'id' => array('type' => 'integer','primary' => '1','autoincrement' => '1','length' => '8',),
			'name' => array('type' => 'string','notnull' => '1','length' => '255',),
			'created_at' => array('notnull' => '1','type' => 'timestamp','length' => '25',),
			'updated_at' => array('notnull' => '1','type' => 'timestamp','length' => '25',),
			),
			array('type' => 'INNODB','primary' => array(0 => 'id',),
		));
		$this->createTable('strain', array(
			'id' => array('type' => 'integer','primary' => '1','autoincrement' => '1','length' => '8',),
			'sample_id' => array('type' => 'integer','notnull' => '1','length' => '8',),
			'dna_id' => array('type' => 'integer','notnull' => '1','length' => '8',),
			'has_dna' => array('type' => 'boolean','notnull' => '1','default' => '0','length' => '25',),
			'is_epitype' => array('type' => 'boolean','notnull' => '1','default' => '0','length' => '25',),
			'is_axenic' => array('type' => 'boolean','notnull' => '1','default' => '0','length' => '25',),
			'is_public' => array('type' => 'boolean','notnull' => '1','default' => '0','length' => '25',),
			'taxonomic_class_id' => array('type' => 'integer','notnull' => '1','length' => '8',),
			'genus_id' => array('type' => 'integer','notnull' => '1','length' => '8',),
			'species_id' => array('type' => 'integer','notnull' => '1','length' => '8',),
			'authority_id' => array('type' => 'integer','notnull' => '1','length' => '8',),
			'isolator_id' => array('type' => 'integer','notnull' => '1','length' => '8',),
			'isolation_date' => array('type' => 'date','notnull' => '1','length' => '25',),
			'depositor_id' => array('type' => 'integer','notnull' => '1','length' => '8',),
			'depositor_date' => array('type' => 'date','notnull' => '1','length' => '25',),
			'identifier_id' => array('type' => 'integer','notnull' => '1','length' => '8',),
			'identification_date' => array('type' => 'date','notnull' => '1','length' => '25',),
			'maintenance_status_id' => array('type' => 'integer','notnull' => '1','length' => '8',),
			'cryopreservation_method_id' => array('type' => 'integer','notnull' => '1','length' => '8',),
			'transfer_interval' => array('type' => 'string','length' => '40',),
			'observation' => array('type' => 'string','length' => '',),
			'citations' => array('type' => 'string','length' => '',),
			'remarks' => array('type' => 'string','length' => '',),
			'created_at' => array('notnull' => '1','type' => 'timestamp','length' => '25',),
			'updated_at' => array('notnull' => '1','type' => 'timestamp','length' => '25',),
			),
			array('type' => 'INNODB','primary' => array(0 => 'id',),
		));
		$this->createTable('strain_growth_mediums', array(
			'strain_id' => array('type' => 'integer','primary' => '1','length' => '8',),
			'growth_medium_id' => array('type' => 'integer','primary' => '1','length' => '8',),
			'created_at' => array('notnull' => '1','type' => 'timestamp','length' => '25',),
			'updated_at' => array('notnull' => '1','type' => 'timestamp','length' => '25',),
			),
			array('type' => 'INNODB','primary' => array(0 => 'strain_id',1 => 'growth_medium_id',),
		));
		$this->createTable('strain_relative', array(
			'id' => array('type' => 'integer','primary' => '1','autoincrement' => '1','length' => '8',),
			'name' => array('type' => 'string','notnull' => '1','length' => '255',),
			'strain_id' => array('type' => 'integer','notnull' => '1','length' => '8',),
			'created_at' => array('notnull' => '1','type' => 'timestamp','length' => '25',),
			'updated_at' => array('notnull' => '1','type' => 'timestamp','length' => '25',),
			),
			array('type' => 'INNODB','primary' => array(0 => 'id',),
		));
	}

	public function down() {
		$this->dropTable('authority');
		$this->dropTable('taxonomic_class');
		$this->dropTable('cryopreservation_method');
		$this->dropTable('depositor');
		$this->dropTable('dna');
		$this->dropTable('genus');
		$this->dropTable('growth_medium');
		$this->dropTable('identifier');
		$this->dropTable('isolator');
		$this->dropTable('maintenance_status');
		$this->dropTable('species');
		$this->dropTable('strain');
		$this->dropTable('strain_growth_mediums');
		$this->dropTable('strain_relative');
	}
}