<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version39 extends Doctrine_Migration_Base {
    public function up() {
        $this->createForeignKey('strain_picture', 'strain_picture_strain_id_strain_id', array(
             'name' => 'strain_picture_strain_id_strain_id',
             'local' => 'strain_id',
             'foreign' => 'id',
             'foreignTable' => 'strain',
             'onUpdate' => '',
             'onDelete' => 'cascade',
             ));
        $this->addIndex('strain_picture', 'strain_picture_strain_id', array(
             'fields' => 
             array(
              0 => 'strain_id',
             ),
             ));
    }

    public function down() {
        $this->dropForeignKey('strain_picture', 'strain_picture_strain_id_strain_id');
        $this->removeIndex('strain_picture', 'strain_picture_strain_id', array(
             'fields' => 
             array(
              0 => 'strain_id',
             ),
             ));
    }
}