<?php
/**
* This class has been auto-generated by the Doctrine ORM Framework
*/
class Version58 extends Doctrine_Migration_Base {
	public function up() {
		$this->createForeignKey('pcr_reaction', 'pcr_reaction_dna_primer_id_dna_primer_id', array(
			'name' => 'pcr_reaction_dna_primer_id_dna_primer_id',
			'local' => 'dna_primer_id',
			'foreign' => 'id',
			'foreignTable' => 'dna_primer',
			));
		$this->createForeignKey('pcr_reaction', 'pcr_reaction_pcr_id_pcr_id', array(
			'name' => 'pcr_reaction_pcr_id_pcr_id',
			'local' => 'pcr_id',
			'foreign' => 'id',
			'foreignTable' => 'pcr',
			'onUpdate' => '',
			'onDelete' => 'cascade',
			));
		$this->addIndex('pcr_reaction', 'pcr_reaction_dna_primer_id', array(
			'fields' => 
		array(
			0 => 'dna_primer_id',
			),
			));
		$this->addIndex('pcr_reaction', 'pcr_reaction_pcr_id', array(
			'fields' => 
		array(
			0 => 'pcr_id',
			),
			));
	}

	public function down() {
		$this->dropForeignKey('pcr_reaction', 'pcr_reaction_dna_primer_id_dna_primer_id');
		$this->dropForeignKey('pcr_reaction', 'pcr_reaction_pcr_id_pcr_id');
		$this->removeIndex('pcr_reaction', 'pcr_reaction_dna_primer_id', array(
			'fields' => 
		array(
			0 => 'dna_primer_id',
			),
			));
		$this->removeIndex('pcr_reaction', 'pcr_reaction_pcr_id', array(
			'fields' => 
		array(
			0 => 'pcr_id',
			),
			));
	}
}