<?php
/**
* This class has been auto-generated by the Doctrine ORM Framework
*/
class Version63 extends Doctrine_Migration_Base {
	public function up() {
		$this->removeColumn('dna_primer', 'strand');
		$this->addColumn('dna_primer', 'name', 'string', '10', array('notnull' => '1'));
		$this->addColumn('dna_primer', 'orientation', 'string', '127', array());
	}

	public function down() {
		$this->addColumn('dna_primer', 'strand', 'string', '10', array('notnull' => '1'));
		$this->removeColumn('dna_primer', 'name');
		$this->removeColumn('dna_primer', 'orientation');
	}
}