<?php
/**
 * Migration file
 *
 * acm : Algae Culture Management (https://github.com/singularfactory/ACM)
 * Copyright 2012, Singular Factory <info@singularfactory.com>
 *
 * This file is part of ACM
 *
 * ACM is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * ACM is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with ACM.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @copyright     Copyright 2012, Singular Factory <info@singularfactory.com>
 * @package       ACM.Lib.Migration
 * @since         1.0
 * @link          https://github.com/singularfactory/ACM
 * @license       GPLv3 License (http://www.gnu.org/licenses/gpl.txt)
 */

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version56 extends Doctrine_Migration_Base {
	public function up() {
		$this->dropTable('dna_sequence_reaction');
		$this->dropTable('dna_sequence');
	}

	public function down() {
		$this->createTable('dna_sequence', array(
			'id' =>
				array(
					'type' => 'integer',
					'primary' => '1',
					'autoincrement' => '1',
					'length' => '8',
					),
					'pcr_id' =>
				array(
					'type' => 'integer',
					'notnull' => '1',
					'length' => '8',
					),
					'gen' =>
				array(
					'type' => 'string',
					'notnull' => '1',
					'length' => '127',
					),
					'date' =>
				array(
					'type' => 'date',
					'notnull' => '1',
					'length' => '25',
					),
					'is_valid' =>
				array(
					'type' => 'boolean',
					'notnull' => '1',
					'default' => '0',
					'length' => '25',
					),
					'remarks' =>
				array(
					'type' => 'string',
					'length' => '',
					),
					'created_at' =>
				array(
					'notnull' => '1',
					'type' => 'timestamp',
					'length' => '25',
					),
					'updated_at' =>
				array(
					'notnull' => '1',
					'type' => 'timestamp',
					'length' => '25',
					),
				), array(
					'type' => 'INNODB',
					'indexes' =>
				array(
					),
					'primary' =>
				array(
					0 => 'id',
					),
					'collate' => 'utf8_general_ci',
					'charset' => 'utf8',
		));

		$this->createForeignKey('dna_sequence', 'dna_sequence_pcr_id_pcr_id', array(
			'name' => 'dna_sequence_pcr_id_pcr_id',
			'local' => 'pcr_id',
			'foreign' => 'id',
			'foreignTable' => 'pcr',
		));

		$this->createTable('dna_sequence_reaction', array(
			'id' =>
				array(
					'type' => 'integer',
					'primary' => '1',
					'autoincrement' => '1',
					'length' => '8',
					),
					'primer' =>
				array(
					'type' => 'string',
					'notnull' => '1',
					'length' => '10',
					),
					'is_valid' =>
				array(
					'type' => 'boolean',
					'notnull' => '1',
					'default' => '0',
					'length' => '25',
					),
					'dna_sequence_id' =>
				array(
					'type' => 'integer',
					'notnull' => '1',
					'length' => '8',
					),
					'created_at' =>
				array(
					'notnull' => '1',
					'type' => 'timestamp',
					'length' => '25',
					),
					'updated_at' =>
				array(
					'notnull' => '1',
					'type' => 'timestamp',
					'length' => '25',
					),
				), array(
					'type' => 'INNODB',
					'indexes' =>
				array(
					),
					'primary' =>
				array(
					0 => 'id',
					),
					'collate' => 'utf8_general_ci',
					'charset' => 'utf8',
			));

		$this->createForeignKey('dna_sequence_reaction', 'dna_sequence_reaction_dna_sequence_id_dna_sequence_id', array(
			'name' => 'dna_sequence_reaction_dna_sequence_id_dna_sequence_id',
			'local' => 'dna_sequence_id',
			'foreign' => 'id',
			'foreignTable' => 'dna_sequence',
			));
	}
}