<?php
/**
* This class has been auto-generated by the Doctrine ORM Framework
*/
class Version50 extends Doctrine_Migration_Base {
	public function up() {
		$this->createTable('dna_primer', array(
			'id' => 
		array(
			'type' => 'integer',
			'primary' => '1',
			'autoincrement' => '1',
			'length' => '8',
			),
			'strand' => 
		array(
			'type' => 'string',
			'notnull' => '1',
			'length' => '10',
			),
			'direction' => 
		array(
			'type' => 'enum',
			'values' => 
		array(
			0 => 'forward',
			1 => 'reverse',
			),
			'length' => '',
			),
			'created_at' => 
		array(
			'notnull' => '1',
			'type' => 'timestamp',
			'length' => '25',
			),
			'updated_at' => 
		array(
			'notnull' => '1',
			'type' => 'timestamp',
			'length' => '25',
			),
		), array(
			'type' => 'INNODB',
			'primary' => 
		array(
			0 => 'id',
			),
			));
		$this->removeColumn('pcr', 'forward_primer');
		$this->removeColumn('pcr', 'reverse_primer');
		$this->addColumn('pcr', 'forward_dna_primer_id', 'integer', '8', array(
			'notnull' => '1',
			));
		$this->addColumn('pcr', 'reverse_dna_primer_id', 'integer', '8', array(
			'notnull' => '1',
			));
	}

	public function down() {
		$this->dropTable('dna_primer');
		$this->addColumn('pcr', 'forward_primer', 'string', '10', array(
			'notnull' => '1',
			));
		$this->addColumn('pcr', 'reverse_primer', 'string', '10', array(
			'notnull' => '1',
			));
		$this->removeColumn('pcr', 'forward_dna_primer_id');
		$this->removeColumn('pcr', 'reverse_dna_primer_id');
	}
}