<?php
/**
* This class has been auto-generated by the Doctrine ORM Framework
*/
class Version81 extends Doctrine_Migration_Base {
	public function up() {
		$this->changeColumn('culture_medium', 'description', 'string', '255', array('notnull' => '1'));
	}

	public function down() {
		$this->changeColumn('culture_medium', 'description', 'string', null, array('notnull' => '1'));
	}
}