<?php
/**
* This class has been auto-generated by the Doctrine ORM Framework
*/
class Version76 extends Doctrine_Migration_Base {
	
	public function up() {
		$this->createForeignKey('strain_culture_media', 'strain_culture_media_culture_medium_id_culture_medium_id', array(
			'name' => 'strain_culture_media_culture_medium_id_culture_medium_id',
			'local' => 'culture_medium_id',
			'foreign' => 'id',
			'foreignTable' => 'culture_medium',
		));
		
		$this->createForeignKey('strain_culture_media', 'strain_culture_media_strain_id_strain_id', array(
			'name' => 'strain_culture_media_strain_id_strain_id',
			'local' => 'strain_id',
			'foreign' => 'id',
			'foreignTable' => 'strain',
		));
		
		$this->addIndex('strain_culture_media', 'strain_culture_media_culture_medium_id', array(
			'fields' => array(0 => 'culture_medium_id',),
		));
		
		$this->addIndex('strain_culture_media', 'strain_culture_media_strain_id', array(
			'fields' => array(0 => 'strain_id',),
		));
	}

	public function down() {
		$this->dropForeignKey('strain_culture_media', 'strain_culture_media_culture_medium_id_culture_medium_id');
		$this->dropForeignKey('strain_culture_media', 'strain_culture_media_strain_id_strain_id');
		$this->removeIndex('strain_culture_media', 'strain_culture_media_culture_medium_id', array(
			'fields' => array(0 => 'culture_medium_id',),
		));
		$this->removeIndex('strain_culture_media', 'strain_culture_media_strain_id', array(
			'fields' => array(0 => 'strain_id',),
		));
	}
}