<?php
/**
 * Migration file
 *
 * acm : Algae Culture Management (https://github.com/singularfactory/ACM)
 * Copyright 2012, Singular Factory <info@singularfactory.com>
 *
 * This file is part of ACM
 *
 * ACM is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * ACM is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with ACM.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @copyright     Copyright 2012, Singular Factory <info@singularfactory.com>
 * @package       ACM.Lib.Migration
 * @since         1.0
 * @link          https://github.com/singularfactory/ACM
 * @license       GPLv3 License (http://www.gnu.org/licenses/gpl.txt)
 */

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version75 extends Doctrine_Migration_Base {

	public function up() {
		$this->dropTable('strain_growth_mediums');
		$this->dropTable('growth_medium');
		$this->createTable('culture_medium', array(
			'id' => array('type' => 'integer','primary' => '1','autoincrement' => '1','length' => '8',),
			'name' => array('type' => 'string','notnull' => '1','length' => '255',),
			'description' => array('type' => 'string','notnull' => '1','length' => '',),
			'link' => array('type' => 'string','notnull' => '1','length' => '1024',),
			'is_public' => array('type' => 'boolean','notnull' => '1','default' => '0','length' => '25',),
			'amount' => array('type' => 'integer','notnull' => '1','default' => '0','length' => '8',),
			'created_at' => array('notnull' => '1','type' => 'timestamp','length' => '25',),
			'updated_at' => array('notnull' => '1','type' => 'timestamp','length' => '25',),
		), array(
			'type' => 'INNODB',
			'primary' => array(0 => 'id',),
			'collate' => 'utf8_general_ci',
			'charset' => 'utf8',
		));

		$this->createTable('strain_culture_media', array(
			'strain_id' => array('type' => 'integer','primary' => '1','length' => '8',),
			'culture_medium_id' => array('type' => 'integer','primary' => '1','length' => '8',),
			'created_at' => array('notnull' => '1','type' => 'timestamp','length' => '25',),
			'updated_at' => array('notnull' => '1','type' => 'timestamp','length' => '25',),
		), array(
			'type' => 'INNODB',
			'primary' => array(0 => 'strain_id', 1 => 'culture_medium_id',),
			'collate' => 'utf8_general_ci',
			'charset' => 'utf8',
		));
	}

	public function down() {
		$this->createTable('growth_medium', array(
			'id' => array('type' => 'integer','primary' => '1','autoincrement' => '1','length' => '8',),
			'name' => array('type' => 'string','notnull' => '1','length' => '255',),
			'description' => array('type' => 'string','notnull' => '1','length' => '',),
			'link' => array('type' => 'string','notnull' => '1','length' => '1024',),
			'is_public' => array('type' => 'boolean','notnull' => '1','default' => '0','length' => '25',),
			'amount' => array('type' => 'integer','notnull' => '1','default' => '0','length' => '8',),
			'created_at' => array('notnull' => '1','type' => 'timestamp','length' => '25',),
			'updated_at' => array('notnull' => '1','type' => 'timestamp','length' => '25',),
		), array(
			'type' => 'INNODB',
			'indexes' => array(),
			'primary' => array(0 => 'id',),
			'collate' => 'utf8_general_ci',
			'charset' => 'utf8',
		));
		$this->createTable('strain_growth_mediums', array(
			'strain_id' => array('type' => 'integer','primary' => '1','length' => '8',),
			'growth_medium_id' => array('type' => 'integer','primary' => '1','length' => '8',),
			'created_at' => array('notnull' => '1','type' => 'timestamp','length' => '25',),
			'updated_at' => array('notnull' => '1','type' => 'timestamp','length' => '25',),
		), array(
			'type' => 'INNODB',
			'indexes' => array(),
			'primary' => array(0 => 'strain_id',1 => 'growth_medium_id',),
			'collate' => 'utf8_general_ci',
			'charset' => 'utf8',
		));

		$this->dropTable('strain_culture_media');
		$this->dropTable('culture_medium');

		$this->createForeignKey('strain_growth_mediums', 'strain_growth_mediums_growth_medium_id_growth_medium_id', array(
			'name' => 'strain_growth_mediums_growth_medium_id_growth_medium_id',
			'local' => 'growth_medium_id',
			'foreign' => 'id',
			'foreignTable' => 'growth_medium',
			));
		$this->createForeignKey('strain_growth_mediums', 'strain_growth_mediums_strain_id_strain_id', array(
			'name' => 'strain_growth_mediums_strain_id_strain_id',
			'local' => 'strain_id',
			'foreign' => 'id',
			'foreignTable' => 'strain',
			'onDelete' => 'cascade',
			));

		$this->addIndex('strain_growth_mediums', 'strain_growth_mediums_growth_medium_id', array(
			'fields' => array(0 => 'growth_medium_id',),
		));
		$this->addIndex('strain_growth_mediums', 'strain_growth_mediums_strain_id', array(
			'fields' => array(0 => 'strain_id',),
		));
	}
}