<?php
/**
* This class has been auto-generated by the Doctrine ORM Framework
*/
class Version71 extends Doctrine_Migration_Base {
	public function up() {
		$this->addColumn('growth_medium', 'amount', 'integer', '8', array('notnull' => '1','default' => '0'));
	}

	public function down() {
		$this->removeColumn('growth_medium', 'amount');
	}
}