<?php
/**
* This class has been auto-generated by the Doctrine ORM Framework
*/
class Version87 extends Doctrine_Migration_Base {
	public function up() {
		$this->createForeignKey('strain', 'strain_container_id_container_id', array(
			'name' => 'strain_container_id_container_id',
			'local' => 'container_id',
			'foreign' => 'id',
			'foreignTable' => 'container',
		));
		$this->addIndex('strain', 'strain_container_id', array('fields' => array(0 => 'container_id')));
	}

	public function down() {
		$this->dropForeignKey('strain', 'strain_container_id_container_id');
		$this->removeIndex('strain', 'strain_container_id', array('fields' => array(0 => 'container_id')));
	}
}