<?php
/**
* This class has been auto-generated by the Doctrine ORM Framework
*/
class Version82 extends Doctrine_Migration_Base {

	public function up(){
		$this->changeColumn('sample', 'radiation_id', 'integer', '8', array());
	}

	public function down(){
		$this->changeColumn('sample', 'radiation_id', 'integer', '8', array('notnull' => true));
	}
}