<?php
/**
 * Migration file
 *
 * acm : Algae Culture Management (https://github.com/singularfactory/ACM)
 * Copyright 2012, Singular Factory <info@singularfactory.com>
 *
 * This file is part of ACM
 *
 * ACM is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * ACM is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with ACM.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @copyright     Copyright 2012, Singular Factory <info@singularfactory.com>
 * @package       ACM.Lib.Migration
 * @since         1.0
 * @link          https://github.com/singularfactory/ACM
 * @license       GPLv3 License (http://www.gnu.org/licenses/gpl.txt)
 */

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version83 extends Doctrine_Migration_Base {

	public function up() {
		$this->addIndex('authority', 'authority_name', array('fields' => array('name' => array('length' => '20'))));
		$this->addIndex('collector', 'collector_name', array('fields' => array('name' => array('length' => '20'))));
		$this->addIndex('collector', 'collector_surname', array('fields' => array('surname' => array('length' => '20'))));
		$this->addIndex('country', 'country_name', array('fields' => array('name' => array('length' => '20'))));
		$this->addIndex('cryopreservation_method', 'cryopreservation_method_name', array('fields' => array('name' => array('length' => '20'))));
		$this->addIndex('culture_medium', 'culture_medium_name', array('fields' => array('name' => array('length' => '20'))));
		$this->addIndex('depositor', 'depositor_name', array('fields' => array('name' => array('length' => '20'))));
		$this->addIndex('depositor', 'depositor_surname', array('fields' => array('surname' => array('length' => '20'))));
		$this->addIndex('dna_extraction', 'dna_extraction_date1', array('fields' => array('extraction_date')));
		$this->addIndex('dna_extraction', 'dna_extraction_date2', array('fields' => array('arrival_date')));
		$this->addIndex('dna_polymerase', 'dna_polymerase_name', array('fields' => array('name' => array('length' => '20'))));
		$this->addIndex('dna_primer', 'dna_primer_name', array('fields' => array('name' => array('length' => '10'))));
		$this->addIndex('environment', 'environment_name', array('fields' => array('name' => array('length' => '20'))));
		$this->addIndex('extraction_kit', 'extraction_kit_name', array('fields' => array('name' => array('length' => '20'))));
		$this->addIndex('genus', 'genus_name', array('fields' => array('name' => array('length' => '20'))));
		$this->addIndex('habitat', 'habitat_name', array('fields' => array('name' => array('length' => '20'))));
		$this->addIndex('identifier', 'identifier_name', array('fields' => array('name' => array('length' => '20'))));
		$this->addIndex('identifier', 'identifier_surname', array('fields' => array('surname' => array('length' => '20'))));
		$this->addIndex('island', 'island_name', array('fields' => array('name' => array('length' => '20'))));
		$this->addIndex('isolator', 'isolator_name', array('fields' => array('name' => array('length' => '20'))));
		$this->addIndex('isolator', 'isolator_surname', array('fields' => array('surname' => array('length' => '20'))));
		$this->addIndex('location', 'location_name', array('fields' => array('name' => array('length' => '20'))));
		$this->addIndex('maintenance_status', 'maintenance_status_name', array('fields' => array('name' => array('length' => '20'))));
		$this->addIndex('notification', 'notification_status', array('fields' => array('status')));
		$this->addIndex('purchase_item', 'purchase_item_status', array('fields' => array('status')));
		$this->addIndex('purchase_order', 'purchase_order_status', array('fields' => array('status')));
		$this->addIndex('radiation', 'radiation_name', array('fields' => array('name' => array('length' => '20'))));
		$this->addIndex('region', 'region_name', array('fields' => array('name' => array('length' => '20'))));
		$this->addIndex('sample', 'sample_notebook_code', array('fields' => array('notebook_code')));
		$this->addIndex('species', 'species_name', array('fields' => array('name' => array('length' => '20'))));
		$this->addIndex('taxonomic_class', 'taxonomic_class_name', array('fields' => array('name' => array('length' => '20'))));
	}

	public function down() {
		$this->removeIndex('authority', 'authority_name', array('fields' => array('name' => array('length' => '20'))));
		$this->removeIndex('collector', 'collector_name', array('fields' => array('name' => array('length' => '20'))));
		$this->removeIndex('collector', 'collector_surname', array('fields' => array('surname' => array('length' => '20'))));
		$this->removeIndex('country', 'country_name', array('fields' => array('name' => array('length' => '20'))));
		$this->removeIndex('cryopreservation_method', 'cryopreservation_method_name', array('fields' => array('name' => array('length' => '20'))));
		$this->removeIndex('culture_medium', 'culture_medium_name', array('fields' => array('name' => array('length' => '20'))));
		$this->removeIndex('depositor', 'depositor_name', array('fields' => array('name' => array('length' => '20'))));
		$this->removeIndex('depositor', 'depositor_surname', array('fields' => array('surname' => array('length' => '20'))));
		$this->removeIndex('dna_extraction', 'dna_extraction_date1', array('fields' => array('extraction_date')));
		$this->removeIndex('dna_extraction', 'dna_extraction_date2', array('fields' => array('arrival_date')));
		$this->removeIndex('dna_polymerase', 'dna_polymerase_name', array('fields' => array('name' => array('length' => '20'))));
		$this->removeIndex('dna_primer', 'dna_primer_name', array('fields' => array('name' => array('length' => '10'))));
		$this->removeIndex('environment', 'environment_name', array('fields' => array('name' => array('length' => '20'))));
		$this->removeIndex('extraction_kit', 'extraction_kit_name', array('fields' => array('name' => array('length' => '20'))));
		$this->removeIndex('genus', 'genus_name', array('fields' => array('name' => array('length' => '20'))));
		$this->removeIndex('habitat', 'habitat_name', array('fields' => array('name' => array('length' => '20'))));
		$this->removeIndex('identifier', 'identifier_name', array('fields' => array('name' => array('length' => '20'))));
		$this->removeIndex('identifier', 'identifier_surname', array('fields' => array('surname' => array('length' => '20'))));
		$this->removeIndex('island', 'island_name', array('fields' => array('name' => array('length' => '20'))));
		$this->removeIndex('isolator', 'isolator_name', array('fields' => array('name' => array('length' => '20'))));
		$this->removeIndex('isolator', 'isolator_surname', array('fields' => array('surname' => array('length' => '20'))));
		$this->removeIndex('location', 'location_name', array('fields' => array('name' => array('length' => '20'))));
		$this->removeIndex('maintenance_status', 'maintenance_status_name', array('fields' => array('name' => array('length' => '20'))));
		$this->removeIndex('notification', 'notification_status', array('fields' => array('status')));
		$this->removeIndex('purchase_item', 'purchase_item_status', array('fields' => array('status')));
		$this->removeIndex('purchase_order', 'purchase_order_status', array('fields' => array('status')));
		$this->removeIndex('radiation', 'radiation_name', array('fields' => array('name' => array('length' => '20'))));
		$this->removeIndex('region', 'region_name', array('fields' => array('name' => array('length' => '20'))));
		$this->removeIndex('sample', 'sample_notebook_code', array('fields' => array('notebook_code')));
		$this->removeIndex('species', 'species_name', array('fields' => array('name' => array('length' => '20'))));
		$this->removeIndex('taxonomic_class', 'taxonomic_class_name', array('fields' => array('name' => array('length' => '20'))));
	}
}
