<?php
/**
* This class has been auto-generated by the Doctrine ORM Framework
*/
class Version109 extends Doctrine_Migration_Base {
	public function up() {
		$this->createTable('maintenance_deposit', array(
			'id' => array('type' => 'integer','primary' => '1','autoincrement' => '1','length' => '8',),
			'taxonomic_class_id' => array('type' => 'integer','notnull' => '1','length' => '8',),
			'genus_id' => array('type' => 'integer','notnull' => '1','length' => '8',),
			'species_id' => array('type' => 'integer','notnull' => '1','length' => '8',),
			'authority_id' => array('type' => 'integer','notnull' => '1','length' => '8',),
			'is_epitype' => array('type' => 'boolean','notnull' => '1','default' => '0','length' => '25',),
			'is_axenic' => array('type' => 'boolean','notnull' => '1','default' => '0','length' => '25',),
			'is_public' => array('type' => 'boolean','notnull' => '1','default' => '0','length' => '25',),
			'has_dna' => array('type' => 'boolean','notnull' => '1','default' => '0','length' => '25',),
			'gen_sequence' => array('type' => 'string','length' => '256',),
			'location_id' => array('type' => 'integer','notnull' => '1','length' => '8',),
			'environment_id' => array('type' => 'integer','notnull' => '1','length' => '8',),
			'habitat_id' => array('type' => 'integer','notnull' => '1','length' => '8',),
			'collection_date' => array('type' => 'date','length' => '25',),
			'isolation_date' => array('type' => 'date','length' => '25',),
			'identifier_id' => array('type' => 'integer','length' => '8',),
			'depositor_id' => array('type' => 'integer','notnull' => '1','length' => '8',),
			'deposition_date' => array('type' => 'date','notnull' => '1','length' => '25',),
			'depositor_code' => array('type' => 'string','notnull' => '1','length' => '40',),
			'maintenance_status_id' => array('type' => 'integer','notnull' => '1','length' => '8',),
			'cryopreservation_method_id' => array('type' => 'integer','length' => '8',),
			'transfer_interval' => array('type' => 'string','length' => '40',),
			'viability_test' => array('type' => 'string','length' => '',),
			'observation' => array('type' => 'string','length' => '',),
			'citations' => array('type' => 'string','length' => '',),
			'remarks' => array('type' => 'string','length' => '',),
			'mf1_link' => array('type' => 'string','notnull' => '1','length' => '1024',),
			'created_at' => array('notnull' => '1','type' => 'timestamp','length' => '25',),
			'updated_at' => array('notnull' => '1','type' => 'timestamp','length' => '25',),
		), array(
			'type' => 'INNODB',
			'primary' => array(0 => 'id',),
			'collate' => 'utf8_general_ci',
			'charset' => 'utf8',
		));
		
		$this->createTable('maintenance_deposit_collectors', array(
			'maintenance_deposit_id' => array('type' => 'integer','primary' => '1','length' => '8',),
			'collector_id' => array('type' => 'integer','primary' => '1','length' => '8',),
			'created_at' => array('notnull' => '1','type' => 'timestamp','length' => '25',),
			'updated_at' => array('notnull' => '1','type' => 'timestamp','length' => '25',),
		), array(
			'type' => 'INNODB',
			'primary' => array(0 => 'maintenance_deposit_id',1 => 'collector_id',),
			'collate' => 'utf8_general_ci',
			'charset' => 'utf8',
		));
		
		$this->createTable('maintenance_deposit_culture_media', array(
			'maintenance_deposit_id' => array('type' => 'integer','primary' => '1','length' => '8',),
			'culture_medium_id' => array('type' => 'integer','primary' => '1','length' => '8',),
			'created_at' => array('notnull' => '1','type' => 'timestamp','length' => '25',),
			'updated_at' => array('notnull' => '1','type' => 'timestamp','length' => '25',),
		), array(
			'type' => 'INNODB',
			'primary' => array(0 => 'maintenance_deposit_id',1 => 'culture_medium_id',),
			'collate' => 'utf8_general_ci',
			'charset' => 'utf8',
		));

		$this->createTable('maintenance_deposit_isolators', array(
			'maintenance_deposit_id' => array('type' => 'integer','primary' => '1','length' => '8',),
			'isolator_id' => array('type' => 'integer','primary' => '1','length' => '8',),
			'created_at' => array('notnull' => '1','type' => 'timestamp','length' => '25',),
			'updated_at' => array('notnull' => '1','type' => 'timestamp','length' => '25',),
		), array(
			'type' => 'INNODB',
			'primary' => array(0 => 'maintenance_deposit_id',1 => 'isolator_id',),
			'collate' => 'utf8_general_ci',
			'charset' => 'utf8',
		));

		$this->createTable('maintenance_deposit_relative', array(
			'id' => array('type' => 'integer','primary' => '1','autoincrement' => '1','length' => '8',),
			'name' => array('type' => 'string','notnull' => '1','length' => '255',),
			'maintenance_deposit_id' => array('type' => 'integer','notnull' => '1','length' => '8',),
			'created_at' => array('notnull' => '1','type' => 'timestamp','length' => '25',),
			'updated_at' => array('notnull' => '1','type' => 'timestamp','length' => '25',),
		), array(
			'type' => 'INNODB',
			'primary' => array(0 => 'id',),
			'collate' => 'utf8_general_ci',
			'charset' => 'utf8',
		));
	}

	public function down() {
		$this->dropTable('maintenance_deposit');
		$this->dropTable('maintenance_deposit_collectors');
		$this->dropTable('maintenance_deposit_culture_media');
		$this->dropTable('maintenance_deposit_isolators');
		$this->dropTable('maintenance_deposit_relative');
	}
}