<?php
/**
* This class has been auto-generated by the Doctrine ORM Framework
*/
class Version95 extends Doctrine_Migration_Base {
	public function up() {
		$this->addColumn('purchase_order', 'customer', 'string', '512', array());
	}

	public function down() {
		$this->removeColumn('purchase_order', 'customer');
	}
}