<?php
/**
* This class has been auto-generated by the Doctrine ORM Framework
*/
class Version101 extends Doctrine_Migration_Base {
	public function up() {
		$this->changeColumn('project', 'inoculation_date', 'date', '25', array('notnull' => '1',));
		$this->changeColumn('project', 'delivery_date', 'date', '25', array());
	}

	public function down() {
		$this->changeColumn('project', 'inoculation_date', 'timestamp', '25', array('notnull' => '1',));
		$this->changeColumn('project', 'delivery_date', 'timestamp', '25', array());
	}
}