<?php
/**
* This class has been auto-generated by the Doctrine ORM Framework
*/
class Version105 extends Doctrine_Migration_Base {
	public function up() {
		$this->changeColumn('patent_deposit', 'depositor_id', 'integer', '8', array('notnull' => '1'));
		$this->changeColumn('patent_deposit', 'deposition_date', 'date', '25', array('notnull' => '1'));
		$this->changeColumn('patent_deposit', 'depositor_code', 'string', '40', array('notnull' => '1'));
	}

	public function down() {
		$this->changeColumn('patent_deposit', 'depositor_id', 'integer', '8', array('notnull' => '0'));
		$this->changeColumn('patent_deposit', 'deposition_date', 'date', '25', array('notnull' => '0'));
		$this->changeColumn('patent_deposit', 'depositor_code', 'string', '40', array('notnull' => '0'));
	}
}