<?php
/**
* This class has been auto-generated by the Doctrine ORM Framework
*/
class Version103 extends Doctrine_Migration_Base {
	public function up() {
		$this->createForeignKey('patent_deposit', 'patent_deposit_taxonomic_class_id_taxonomic_class_id', array(
			'name' => 'patent_deposit_taxonomic_class_id_taxonomic_class_id',
			'local' => 'taxonomic_class_id',
			'foreign' => 'id',
			'foreignTable' => 'taxonomic_class',
		));
		$this->createForeignKey('patent_deposit', 'patent_deposit_genus_id_genus_id', array(
			'name' => 'patent_deposit_genus_id_genus_id',
			'local' => 'genus_id',
			'foreign' => 'id',
			'foreignTable' => 'genus',
		));
		$this->createForeignKey('patent_deposit', 'patent_deposit_species_id_species_id', array(
			'name' => 'patent_deposit_species_id_species_id',
			'local' => 'species_id',
			'foreign' => 'id',
			'foreignTable' => 'species',
		));
		$this->createForeignKey('patent_deposit', 'patent_deposit_authority_id_authority_id', array(
			'name' => 'patent_deposit_authority_id_authority_id',
			'local' => 'authority_id',
			'foreign' => 'id',
			'foreignTable' => 'authority',
		));
		$this->createForeignKey('patent_deposit', 'patent_deposit_location_id_location_id', array(
			'name' => 'patent_deposit_location_id_location_id',
			'local' => 'location_id',
			'foreign' => 'id',
			'foreignTable' => 'location',
		));
		$this->createForeignKey('patent_deposit', 'patent_deposit_environment_id_environment_id', array(
			'name' => 'patent_deposit_environment_id_environment_id',
			'local' => 'environment_id',
			'foreign' => 'id',
			'foreignTable' => 'environment',
		));
		$this->createForeignKey('patent_deposit', 'patent_deposit_habitat_id_habitat_id', array(
			'name' => 'patent_deposit_habitat_id_habitat_id',
			'local' => 'habitat_id',
			'foreign' => 'id',
			'foreignTable' => 'habitat',
		));
		$this->createForeignKey('patent_deposit', 'patent_deposit_identifier_id_identifier_id', array(
			'name' => 'patent_deposit_identifier_id_identifier_id',
			'local' => 'identifier_id',
			'foreign' => 'id',
			'foreignTable' => 'identifier',
		));
		$this->createForeignKey('patent_deposit', 'patent_deposit_depositor_id_depositor_id', array(
			'name' => 'patent_deposit_depositor_id_depositor_id',
			'local' => 'depositor_id',
			'foreign' => 'id',
			'foreignTable' => 'depositor',
		));
		$this->createForeignKey('patent_deposit', 'patent_deposit_maintenance_status_id_maintenance_status_id', array(
			'name' => 'patent_deposit_maintenance_status_id_maintenance_status_id',
			'local' => 'maintenance_status_id',
			'foreign' => 'id',
			'foreignTable' => 'maintenance_status',
		));
		$this->createForeignKey('patent_deposit', 'pcci', array(
			'name' => 'pcci',
			'local' => 'cryopreservation_method_id',
			'foreign' => 'id',
			'foreignTable' => 'cryopreservation_method',
		));
		$this->createForeignKey('patent_deposit_collectors', 'patent_deposit_collectors_patent_deposit_id_patent_deposit_id', array(
			'name' => 'patent_deposit_collectors_patent_deposit_id_patent_deposit_id',
			'local' => 'patent_deposit_id',
			'foreign' => 'id',
			'foreignTable' => 'patent_deposit',
			'onUpdate' => '',
			'onDelete' => 'cascade',
		));
		$this->createForeignKey('patent_deposit_culture_media', 'patent_deposit_culture_media_patent_deposit_id_patent_deposit_id', array(
			'name' => 'patent_deposit_culture_media_patent_deposit_id_patent_deposit_id',
			'local' => 'patent_deposit_id',
			'foreign' => 'id',
			'foreignTable' => 'patent_deposit',
			'onUpdate' => '',
			'onDelete' => 'cascade',
		));
		$this->createForeignKey('patent_deposit_isolators', 'patent_deposit_isolators_patent_deposit_id_patent_deposit_id', array(
			'name' => 'patent_deposit_isolators_patent_deposit_id_patent_deposit_id',
			'local' => 'patent_deposit_id',
			'foreign' => 'id',
			'foreignTable' => 'patent_deposit',
			'onUpdate' => '',
			'onDelete' => 'cascade',
		));
		$this->createForeignKey('patent_deposit_relative', 'patent_deposit_relative_patent_deposit_id_patent_deposit_id', array(
			'name' => 'patent_deposit_relative_patent_deposit_id_patent_deposit_id',
			'local' => 'patent_deposit_id',
			'foreign' => 'id',
			'foreignTable' => 'patent_deposit',
			'onUpdate' => '',
			'onDelete' => 'cascade',
		));
		$this->addIndex('patent_deposit', 'patent_deposit_taxonomic_class_id', array('fields' => array(0 => 'taxonomic_class_id',),));
		$this->addIndex('patent_deposit', 'patent_deposit_genus_id', array('fields' => array(0 => 'genus_id',),));
		$this->addIndex('patent_deposit', 'patent_deposit_species_id', array('fields' => array(0 => 'species_id',),));
		$this->addIndex('patent_deposit', 'patent_deposit_authority_id', array('fields' => array(0 => 'authority_id',),));
		$this->addIndex('patent_deposit', 'patent_deposit_location_id', array('fields' => array(0 => 'location_id',),));
		$this->addIndex('patent_deposit', 'patent_deposit_environment_id', array('fields' => array(0 => 'environment_id',),));
		$this->addIndex('patent_deposit', 'patent_deposit_habitat_id', array('fields' => array(0 => 'habitat_id',),));
		$this->addIndex('patent_deposit', 'patent_deposit_identifier_id', array('fields' => array(0 => 'identifier_id',),));
		$this->addIndex('patent_deposit', 'patent_deposit_depositor_id', array('fields' => array(0 => 'depositor_id',),));
		$this->addIndex('patent_deposit', 'patent_deposit_maintenance_status_id', array('fields' => array(0 => 'maintenance_status_id',),));
		$this->addIndex('patent_deposit', 'patent_deposit_cryopreservation_method_id', array('fields' => array(0 => 'cryopreservation_method_id',),));
		$this->addIndex('patent_deposit_collectors', 'patent_deposit_collectors_patent_deposit_id', array('fields' => array(0 => 'patent_deposit_id',),));
		$this->addIndex('patent_deposit_culture_media', 'patent_deposit_culture_media_patent_deposit_id', array('fields' => array(0 => 'patent_deposit_id',),));
		$this->addIndex('patent_deposit_isolators', 'patent_deposit_isolators_patent_deposit_id', array('fields' => array(0 => 'patent_deposit_id',),));
		$this->addIndex('patent_deposit_relative', 'patent_deposit_relative_patent_deposit_id', array('fields' => array(0 => 'patent_deposit_id',),));
	}

	public function down() {
		$this->dropForeignKey('patent_deposit', 'patent_deposit_taxonomic_class_id_taxonomic_class_id');
		$this->dropForeignKey('patent_deposit', 'patent_deposit_genus_id_genus_id');
		$this->dropForeignKey('patent_deposit', 'patent_deposit_species_id_species_id');
		$this->dropForeignKey('patent_deposit', 'patent_deposit_authority_id_authority_id');
		$this->dropForeignKey('patent_deposit', 'patent_deposit_location_id_location_id');
		$this->dropForeignKey('patent_deposit', 'patent_deposit_environment_id_environment_id');
		$this->dropForeignKey('patent_deposit', 'patent_deposit_habitat_id_habitat_id');
		$this->dropForeignKey('patent_deposit', 'patent_deposit_identifier_id_identifier_id');
		$this->dropForeignKey('patent_deposit', 'patent_deposit_depositor_id_depositor_id');
		$this->dropForeignKey('patent_deposit', 'patent_deposit_maintenance_status_id_maintenance_status_id');
		$this->dropForeignKey('patent_deposit', 'pcci');
		$this->dropForeignKey('patent_deposit_collectors', 'patent_deposit_collectors_patent_deposit_id_patent_deposit_id');
		$this->dropForeignKey('patent_deposit_culture_media', 'patent_deposit_culture_media_patent_deposit_id_patent_deposit_id');
		$this->dropForeignKey('patent_deposit_isolators', 'patent_deposit_isolators_patent_deposit_id_patent_deposit_id');
		$this->dropForeignKey('patent_deposit_relative', 'patent_deposit_relative_patent_deposit_id_patent_deposit_id');
		$this->removeIndex('patent_deposit', 'patent_deposit_taxonomic_class_id', array('fields' => array(0 => 'taxonomic_class_id',),));
		$this->removeIndex('patent_deposit', 'patent_deposit_genus_id', array('fields' => array(0 => 'genus_id',),));
		$this->removeIndex('patent_deposit', 'patent_deposit_species_id', array('fields' => array(0 => 'species_id',),));
		$this->removeIndex('patent_deposit', 'patent_deposit_authority_id', array('fields' => array(0 => 'authority_id',),));
		$this->removeIndex('patent_deposit', 'patent_deposit_location_id', array('fields' => array(0 => 'location_id',),));
		$this->removeIndex('patent_deposit', 'patent_deposit_environment_id', array('fields' => array(0 => 'environment_id',),));
		$this->removeIndex('patent_deposit', 'patent_deposit_habitat_id', array('fields' => array(0 => 'habitat_id',),));
		$this->removeIndex('patent_deposit', 'patent_deposit_identifier_id', array('fields' => array(0 => 'identifier_id',),));
		$this->removeIndex('patent_deposit', 'patent_deposit_depositor_id', array('fields' => array(0 => 'depositor_id',),));
		$this->removeIndex('patent_deposit', 'patent_deposit_maintenance_status_id', array('fields' => array(0 => 'maintenance_status_id',),));
		$this->removeIndex('patent_deposit', 'patent_deposit_cryopreservation_method_id', array('fields' => array(0 => 'cryopreservation_method_id',),));
		$this->removeIndex('patent_deposit_collectors', 'patent_deposit_collectors_patent_deposit_id', array('fields' => array(0 => 'patent_deposit_id',),));
		$this->removeIndex('patent_deposit_culture_media', 'patent_deposit_culture_media_patent_deposit_id', array('fields' => array(0 => 'patent_deposit_id',),));
		$this->removeIndex('patent_deposit_isolators', 'patent_deposit_isolators_patent_deposit_id', array('fields' => array(0 => 'patent_deposit_id',),));
		$this->removeIndex('patent_deposit_relative', 'patent_deposit_relative_patent_deposit_id', array('fields' => array(0 => 'patent_deposit_id',),));
	}
}