<?php
/**
* This class has been auto-generated by the Doctrine ORM Framework
*/
class Version117 extends Doctrine_Migration_Base {
	public function up() {
		$this->addColumn('purchase_order', 'delivery_code', 'string', '80', array());
	}

	public function down() {
		$this->removeColumn('purchase_order', 'delivery_code');
	}
}