<?php
/**
* This class has been auto-generated by the Doctrine ORM Framework
*/
class Version127 extends Doctrine_Migration_Base {
	public function up() {
		$this->addColumn('project', 'petitioner_id', 'integer', '8', array('notnull' => '1'));
	}

	public function down() {
		$this->removeColumn('project', 'petitioner_id');
	}
}