<?php
/**
* This class has been auto-generated by the Doctrine ORM Framework
*/
class Version130 extends Doctrine_Migration_Base {
	public function up() {
		$this->addColumn('project', 'subject', 'enum', '', array('values' => array(
			0 => 'sample',
			1 => 'strain',
		)));
		$this->addColumn('project', 'sample_id', 'integer', '8', array());
		$this->changeColumn('project', 'strain_id', 'integer', '8', array());
	}

	public function down() {
		$this->removeColumn('project', 'subject');
		$this->removeColumn('project', 'sample_id');
		$this->changeColumn('project', 'strain_id', 'integer', '8', array('notnull' => '1'));
	}
}