<?php
/**
* This class has been auto-generated by the Doctrine ORM Framework
*/
class Version125 extends Doctrine_Migration_Base {
	public function up() {
		$this->addColumn('strain', 'code', 'integer', '8', array('notnull' => '1',));
		$this->addColumn('strain', 'clone_number', 'integer', '8', array());
		
		$this->addIndex('strain', 'unique_code_and_clone', array(
			'fields' => array(0 => 'code',1 => 'clone_number',),
			'type' => 'unique',
		));
	}
	
	public function postUp() {
		echo ">> postUp(): initializing code column in strain table\n";
		foreach ( StrainTable::getInstance()->createQuery('s')->select('s.id, s.code')->execute() as $strain ) {
			$strain->setCode($strain->getId());
			if ( $strain->trySave() ) {
				echo ">> postUp(): id {$strain->getId()} => code {$strain->getCode()}\n";
			}
		}
	}

	public function down() {
		$this->removeIndex('strain', 'unique_code_and_clone', array(
			'fields' => array(0 => 'code',1 => 'clone_number',),
			'type' => 'unique',
		));
		
		$this->removeColumn('strain', 'code');
		$this->removeColumn('strain', 'clone_number');
	}
}