<?php
/**
* This class has been auto-generated by the Doctrine ORM Framework
*/
class Version140 extends Doctrine_Migration_Base {
	public function up(){
		$this->addColumn('strain', 'supervisor_id', 'integer', '8', array());
	}

	public function down() {
		$this->removeColumn('strain', 'supervisor_id');
	}
}