<?php
/**
* This class has been auto-generated by the Doctrine ORM Framework
*/
class Version149 extends Doctrine_Migration_Base {
	public function up() {
		$this->createForeignKey('cryopreservation', 'cryopreservation_sample_id_sample_id', array(
			'name' => 'cryopreservation_sample_id_sample_id',
			'local' => 'sample_id',
			'foreign' => 'id',
			'foreignTable' => 'sample',
		));
		$this->createForeignKey('cryopreservation', 'cryopreservation_strain_id_strain_id', array(
			'name' => 'cryopreservation_strain_id_strain_id',
			'local' => 'strain_id',
			'foreign' => 'id',
			'foreignTable' => 'strain',
		));
		$this->createForeignKey('cryopreservation', 'ccci', array(
			'name' => 'ccci',
			'local' => 'cryopreservation_method_id',
			'foreign' => 'id',
			'foreignTable' => 'cryopreservation_method',
		));
		$this->addIndex('cryopreservation', 'cryopreservation_sample_id', array('fields' => array(0 => 'sample_id',),));
		$this->addIndex('cryopreservation', 'cryopreservation_strain_id', array('fields' => array(0 => 'strain_id',),));
		$this->addIndex('cryopreservation', 'cryopreservation_cryopreservation_method_id', array('fields' => array(0 => 'cryopreservation_method_id',),));
	}

	public function down() {
		$this->dropForeignKey('cryopreservation', 'cryopreservation_sample_id_sample_id');
		$this->dropForeignKey('cryopreservation', 'cryopreservation_strain_id_strain_id');
		$this->dropForeignKey('cryopreservation', 'ccci');
		$this->removeIndex('cryopreservation', 'cryopreservation_sample_id', array('fields' => array(0 => 'sample_id',),));
		$this->removeIndex('cryopreservation', 'cryopreservation_strain_id', array('fields' => array(0 => 'strain_id',),));
		$this->removeIndex('cryopreservation', 'cryopreservation_cryopreservation_method_id', array('fields' => array(0 => 'cryopreservation_method_id',),));
	}
}