<?php
/**
* This class has been auto-generated by the Doctrine ORM Framework
*/
class Version152 extends Doctrine_Migration_Base {
	public function up() {
		$this->createForeignKey('identification', 'identification_sample_id_sample_id', array(
			'name' => 'identification_sample_id_sample_id',
			'local' => 'sample_id',
			'foreign' => 'id',
			'foreignTable' => 'sample',
		));
		$this->addIndex('identification', 'identification_sample_id', array('fields' => array(0 => 'sample_id',),));
	}

	public function down() {
		$this->dropForeignKey('identification', 'identification_sample_id_sample_id');
		$this->removeIndex('identification', 'identification_sample_id', array('fields' => array(0 => 'sample_id',),));
	}
}