<?php
/**
* This class has been auto-generated by the Doctrine ORM Framework
*/
class Version151 extends Doctrine_Migration_Base {
	public function up() {
		$this->createTable('identification', array(
			'id' => array('type' => 'integer','primary' => '1','autoincrement' => '1','length' => '8'),
			'identification_date' => array('type' => 'date','notnull' => '1','length' => '25'),
			'sample_id' => array('type' => 'integer','notnull' => '1','length' => '8'),
			'petitioner' => array('type' => 'string','length' => '255'),
			'sample_picture' => array('type' => 'string','length' => '255'),
			'microscopy_identification' => array('type' => 'string','length' => '255'),
			'molecular_identification' => array('type' => 'string','length' => '255'),
			'request_document' => array('type' => 'string','length' => '255'),
			'report_document' => array('type' => 'string','length' => '255'),
			'remarks' => array('type' => 'string','length' => ''),
			'created_at' => array('notnull' => '1','type' => 'timestamp','length' => '25'),
			'updated_at' => array('notnull' => '1','type' => 'timestamp','length' => '25'),
		),
		array(
			'type' => 'INNODB',
			'indexes' => array('identification_date' => array('fields' => array(0 => 'identification_date'))),
			'primary' => array(0 => 'id'),
			'collate' => 'utf8_general_ci',
			'charset' => 'utf8',
		));
	}

	public function down() {
		$this->dropTable('identification');
	}
}