<?php
/**
* This class has been auto-generated by the Doctrine ORM Framework
*/
class Version159 extends Doctrine_Migration_Base {
	public function up() {
		$this->addColumn('sf_guard_user', 'initials', 'string', '5', array('notnull' => '1'));
	}

	public function down() {
		$this->removeColumn('sf_guard_user', 'initials');
	}
}