<?php
/**
* This class has been auto-generated by the Doctrine ORM Framework
*/
class Version162 extends Doctrine_Migration_Base {
	public function up() {
		$this->addColumn('strain', 'kingdom_id', 'integer', '8', array());
		$this->addColumn('strain', 'subkingdom_id', 'integer', '8', array());
		$this->addColumn('strain', 'phylum_id', 'integer', '8', array());
		$this->addColumn('strain', 'taxonomic_order_id', 'integer', '8', array());
		$this->addColumn('strain', 'family_id', 'integer', '8', array());
	}

	public function down() {
		$this->removeColumn('strain', 'kingdom_id');
		$this->removeColumn('strain', 'subkingdom_id');
		$this->removeColumn('strain', 'phylum_id');
		$this->removeColumn('strain', 'taxonomic_order_id');
		$this->removeColumn('strain', 'family_id');
	}
}