<?php
/**
* This class has been auto-generated by the Doctrine ORM Framework
*/
class Version161 extends Doctrine_Migration_Base {
	public function up() {
		$this->createTable('family', array(
			'id' => array('type' => 'integer','primary' => '1','autoincrement' => '1','length' => '8',),
			'name' => array('type' => 'string','notnull' => '1','length' => '255',),
			'created_at' => array('notnull' => '1','type' => 'timestamp','length' => '25',),
			'updated_at' => array('notnull' => '1','type' => 'timestamp','length' => '25',),
		),
			array(
			'type' => 'INNODB',
			'indexes' => array('family_name' => array('fields' => array('name' => array('length' => '20',),),),),
			'primary' => array(0 => 'id',),
			'collate' => 'utf8_general_ci',
			'charset' => 'utf8',
		));
		$this->createTable('kingdom', array(
			'id' => array('type' => 'integer','primary' => '1','autoincrement' => '1','length' => '8',),
			'name' => array('type' => 'string','notnull' => '1','length' => '255',),
			'created_at' => array('notnull' => '1','type' => 'timestamp','length' => '25',),
			'updated_at' => array('notnull' => '1','type' => 'timestamp','length' => '25',),
			),
			array(
			'type' => 'INNODB',
			'indexes' => array('kingdom_name' => array('fields' => array('name' => array('length' => '20',),),),),
			'primary' => array(0 => 'id',),
			'collate' => 'utf8_general_ci',
			'charset' => 'utf8',
		));
		$this->createTable('phylum', array(
			'id' => array('type' => 'integer','primary' => '1','autoincrement' => '1','length' => '8',),
			'name' => array('type' => 'string','notnull' => '1','length' => '255',),
			'created_at' => array('notnull' => '1','type' => 'timestamp','length' => '25',),
			'updated_at' => array('notnull' => '1','type' => 'timestamp','length' => '25',),
		), array(
			'type' => 'INNODB',
			'indexes' => array('phylum_name' => array('fields' => array('name' => array('length' => '20',),),),),
			'primary' => array(0 => 'id',),
			'collate' => 'utf8_general_ci',
			'charset' => 'utf8',
		));
		$this->createTable('subkingdom', array(
			'id' => array('type' => 'integer','primary' => '1','autoincrement' => '1','length' => '8',),
			'name' => array('type' => 'string','notnull' => '1','length' => '255',),
			'created_at' => array('notnull' => '1','type' => 'timestamp','length' => '25',),
			'updated_at' => array('notnull' => '1','type' => 'timestamp','length' => '25',),
		), array(
			'type' => 'INNODB',
			'indexes' => array('subkingdom_name' => array('fields' => array('name' => array('length' => '20',),),),),
			'primary' => array(0 => 'id',),
			'collate' => 'utf8_general_ci',
			'charset' => 'utf8',
		));
		$this->createTable('taxonomic_order', array(
			'id' => array('type' => 'integer','primary' => '1','autoincrement' => '1','length' => '8',),
			'name' => array('type' => 'string','notnull' => '1','length' => '255',),
			'created_at' => array('notnull' => '1','type' => 'timestamp','length' => '25',),
			'updated_at' => array('notnull' => '1','type' => 'timestamp','length' => '25',),
		), array(
			'type' => 'INNODB',
			'indexes' => array('taxonomic_order_name' => array('fields' => array('name' => array('length' => '20',),),),),
			'primary' => array(0 => 'id',),
			'collate' => 'utf8_general_ci',
			'charset' => 'utf8',
		));
	}

	public function down() {
		$this->dropTable('family');
		$this->dropTable('kingdom');
		$this->dropTable('phylum');
		$this->dropTable('subkingdom');
		$this->dropTable('taxonomic_order');
	}
}