<?php
/**
* This class has been auto-generated by the Doctrine ORM Framework
*/
class Version163 extends Doctrine_Migration_Base {
	public function up() {
		$this->createForeignKey('external_strain', 'external_strain_supervisor_id_sf_guard_user_id', array(
			'name' => 'external_strain_supervisor_id_sf_guard_user_id',
			'local' => 'supervisor_id',
			'foreign' => 'id',
			'foreignTable' => 'sf_guard_user',
		));
	}

	public function down() {
		$this->dropForeignKey('external_strain', 'external_strain_supervisor_id_sf_guard_user_id');
	}
}