<?php
/**
* This class has been auto-generated by the Doctrine ORM Framework
*/
class Version175 extends Doctrine_Migration_Base {
	public function up() {
		$this->addColumn('strain', 'habitat_description', 'string', '', array());
	}

	public function down() {
		$this->removeColumn('strain', 'habitat_description');
	}
}