<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version182 extends Doctrine_Migration_Base {
	public function up() {
		$this->addColumn('strain', 'culture_medium_id', 'integer', '8', array());
	}

	public function down() {
		$this->removeColumn('strain', 'culture_medium_id');
	}
}
