<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version177 extends Doctrine_Migration_Base {
	public function up() {
		$this->changeColumn('maintenance_deposit', 'species_id', 'integer', '8', array('notnull' => '0'));
		$this->changeColumn('patent_deposit', 'species_id', 'integer', '8', array('notnull' => '0'));
		$this->changeColumn('strain', 'species_id', 'integer', '8', array('notnull' => '0'));
	}

	public function down() {
		$this->changeColumn('maintenance_deposit', 'species_id', 'integer', '8', array('notnull' => '1'));
		$this->changeColumn('patent_deposit', 'species_id', 'integer', '8', array('notnull' => '1'));
		$this->changeColumn('strain', 'species_id', 'integer', '8', array('notnull' => '1'));
	}
}
