<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version180 extends Doctrine_Migration_Base {
	public function up() {
		$this->createForeignKey('external_strain', 'external_strain_sample_id_sample_id', array(
			'name' => 'external_strain_sample_id_sample_id',
			'local' => 'sample_id',
			'foreign' => 'id',
			'foreignTable' => 'sample',
		));
		$this->createForeignKey('external_strain', 'external_strain_depositor_id_depositor_id', array(
			'name' => 'external_strain_depositor_id_depositor_id',
			'local' => 'depositor_id',
			'foreign' => 'id',
			'foreignTable' => 'depositor',
		));
		$this->createForeignKey('external_strain', 'external_strain_kingdom_id_kingdom_id', array(
			'name' => 'external_strain_kingdom_id_kingdom_id',
			'local' => 'kingdom_id',
			'foreign' => 'id',
			'foreignTable' => 'kingdom',
		));
		$this->createForeignKey('external_strain', 'external_strain_subkingdom_id_subkingdom_id', array(
			'name' => 'external_strain_subkingdom_id_subkingdom_id',
			'local' => 'subkingdom_id',
			'foreign' => 'id',
			'foreignTable' => 'subkingdom',
		));
		$this->createForeignKey('external_strain', 'external_strain_phylum_id_phylum_id', array(
			'name' => 'external_strain_phylum_id_phylum_id',
			'local' => 'phylum_id',
			'foreign' => 'id',
			'foreignTable' => 'phylum',
		));
		$this->createForeignKey('external_strain', 'external_strain_taxonomic_order_id_taxonomic_order_id', array(
			'name' => 'external_strain_taxonomic_order_id_taxonomic_order_id',
			'local' => 'taxonomic_order_id',
			'foreign' => 'id',
			'foreignTable' => 'taxonomic_order',
		));
		$this->createForeignKey('external_strain', 'external_strain_family_id_family_id', array(
			'name' => 'external_strain_family_id_family_id',
			'local' => 'family_id',
			'foreign' => 'id',
			'foreignTable' => 'family',
		));
		$this->addIndex('external_strain', 'external_strain_sample_id', array( 'fields' => array( 0 => 'sample_id',),));
		$this->addIndex('external_strain', 'external_strain_depositor_id', array( 'fields' => array( 0 => 'depositor_id',),));
		$this->addIndex('external_strain', 'external_strain_kingdom_id', array( 'fields' => array( 0 => 'kingdom_id',),));
		$this->addIndex('external_strain', 'external_strain_subkingdom_id', array( 'fields' => array( 0 => 'subkingdom_id',),));
		$this->addIndex('external_strain', 'external_strain_phylum_id', array( 'fields' => array( 0 => 'phylum_id',),));
		$this->addIndex('external_strain', 'external_strain_taxonomic_order_id', array( 'fields' => array( 0 => 'taxonomic_order_id',),));
		$this->addIndex('external_strain', 'external_strain_family_id', array( 'fields' => array( 0 => 'family_id',),));
	}

	public function down() {
		$this->dropForeignKey('external_strain', 'external_strain_sample_id_sample_id');
		$this->dropForeignKey('external_strain', 'external_strain_depositor_id_depositor_id');
		$this->dropForeignKey('external_strain', 'external_strain_kingdom_id_kingdom_id');
		$this->dropForeignKey('external_strain', 'external_strain_subkingdom_id_subkingdom_id');
		$this->dropForeignKey('external_strain', 'external_strain_phylum_id_phylum_id');
		$this->dropForeignKey('external_strain', 'external_strain_taxonomic_order_id_taxonomic_order_id');
		$this->dropForeignKey('external_strain', 'external_strain_family_id_family_id');
	}
}
