<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version212 extends Doctrine_Migration_Base {
	public function up() {
		$this->createForeignKey('potential_usages', 'potential_usages_strain_taxonomy_id_strain_taxonomy_id', array(
			'name' => 'potential_usages_strain_taxonomy_id_strain_taxonomy_id',
			'local' => 'strain_taxonomy_id',
			'foreign' => 'id',
			'foreignTable' => 'strain_taxonomy',
			'onUpdate' => 'cascade',
			'onDelete' => 'cascade',
		));
		$this->createForeignKey('strain_taxonomy', 'strain_taxonomy_taxonomic_class_id_taxonomic_class_id', array(
			'name' => 'strain_taxonomy_taxonomic_class_id_taxonomic_class_id',
			'local' => 'taxonomic_class_id',
			'foreign' => 'id',
			'foreignTable' => 'taxonomic_class',
		));
		$this->createForeignKey('strain_taxonomy', 'strain_taxonomy_genus_id_genus_id', array(
			'name' => 'strain_taxonomy_genus_id_genus_id',
			'local' => 'genus_id',
			'foreign' => 'id',
			'foreignTable' => 'genus',
		));
		$this->createForeignKey('strain_taxonomy', 'strain_taxonomy_species_id_species_id', array(
			'name' => 'strain_taxonomy_species_id_species_id',
			'local' => 'species_id',
			'foreign' => 'id',
			'foreignTable' => 'species',
		));
		$this->createForeignKey('usage_area_usage_targets', 'usage_area_usage_targets_usage_area_id_usage_area_id', array(
			'name' => 'usage_area_usage_targets_usage_area_id_usage_area_id',
			'local' => 'usage_area_id',
			'foreign' => 'id',
			'foreignTable' => 'usage_area',
			'onUpdate' => 'cascade',
			'onDelete' => 'cascade',
		));
		$this->createForeignKey('usage_area_usage_targets', 'usage_area_usage_targets_usage_target_id_usage_target_id', array(
			'name' => 'usage_area_usage_targets_usage_target_id_usage_target_id',
			'local' => 'usage_target_id',
			'foreign' => 'id',
			'foreignTable' => 'usage_target',
			'onUpdate' => 'cascade',
			'onDelete' => 'cascade',
		));
		//$this->addIndex('potential_usages', 'potential_usages_strain_taxonomy_id', array( 'fields' => array( 0 => 'strain_taxonomy_id',),));
		//$this->addIndex('strain_taxonomy', 'strain_taxonomy_taxonomic_class_id', array( 'fields' => array( 0 => 'taxonomic_class_id',),));
		//$this->addIndex('strain_taxonomy', 'strain_taxonomy_genus_id', array( 'fields' => array( 0 => 'genus_id',),));
		//$this->addIndex('strain_taxonomy', 'strain_taxonomy_species_id', array( 'fields' => array( 0 => 'species_id',),));
		//$this->addIndex('usage_area_usage_targets', 'usage_area_usage_targets_usage_area_id', array( 'fields' => array( 0 => 'usage_area_id',),));
		//$this->addIndex('usage_area_usage_targets', 'usage_area_usage_targets_usage_target_id', array( 'fields' => array( 0 => 'usage_target_id',),));
	}

	public function down() {
		$this->dropForeignKey('potential_usages', 'potential_usages_strain_taxonomy_id_strain_taxonomy_id');
		$this->dropForeignKey('strain_taxonomy', 'strain_taxonomy_taxonomic_class_id_taxonomic_class_id');
		$this->dropForeignKey('strain_taxonomy', 'strain_taxonomy_genus_id_genus_id');
		$this->dropForeignKey('strain_taxonomy', 'strain_taxonomy_species_id_species_id');
		$this->dropForeignKey('usage_area_usage_targets', 'usage_area_usage_targets_usage_area_id_usage_area_id');
		$this->dropForeignKey('usage_area_usage_targets', 'usage_area_usage_targets_usage_target_id_usage_target_id');
		//$this->removeIndex('potential_usages', 'potential_usages_strain_taxonomy_id', array( 'fields' => array( 0 => 'strain_taxonomy_id',),));
		//$this->removeIndex('strain_taxonomy', 'strain_taxonomy_taxonomic_class_id', array( 'fields' => array( 0 => 'taxonomic_class_id',),));
		//$this->removeIndex('strain_taxonomy', 'strain_taxonomy_genus_id', array( 'fields' => array( 0 => 'genus_id',),));
		//$this->removeIndex('strain_taxonomy', 'strain_taxonomy_species_id', array( 'fields' => array( 0 => 'species_id',),));
		//$this->removeIndex('usage_area_usage_targets', 'usage_area_usage_targets_usage_area_id', array( 'fields' => array( 0 => 'usage_area_id',),));
		//$this->removeIndex('usage_area_usage_targets', 'usage_area_usage_targets_usage_target_id', array( 'fields' => array( 0 => 'usage_target_id',),));
	}
}
