<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version203 extends Doctrine_Migration_Base {
	public function up() {
		$this->dropForeignKey('cryopreservation', 'cryopreservation_strain_id_strain_id');
		$this->dropForeignKey('dna_extraction', 'dna_extraction_strain_id_strain_id');
		$this->dropForeignKey('isolation', 'isolation_strain_id_strain_id');
		$this->dropForeignKey('project', 'project_strain_id_strain_id');

		$this->createForeignKey('cryopreservation', 'cryopreservation_strain_id_strain_id', array(
			'name' => 'cryopreservation_strain_id_strain_id',
			'local' => 'strain_id',
			'foreign' => 'id',
			'foreignTable' => 'strain',
			'onUpdate' => 'cascade',
			'onDelete' => '',
		));
		$this->createForeignKey('dna_extraction', 'dna_extraction_strain_id_strain_id', array(
			'name' => 'dna_extraction_strain_id_strain_id',
			'local' => 'strain_id',
			'foreign' => 'id',
			'foreignTable' => 'strain',
			'onUpdate' => 'cascade',
			'onDelete' => '',
		));
		$this->createForeignKey('isolation', 'isolation_strain_id_strain_id', array(
			'name' => 'isolation_strain_id_strain_id',
			'local' => 'strain_id',
			'foreign' => 'id',
			'foreignTable' => 'strain',
			'onUpdate' => 'cascade',
			'onDelete' => '',
		));
		$this->createForeignKey('project', 'project_strain_id_strain_id', array(
			'name' => 'project_strain_id_strain_id',
			'local' => 'strain_id',
			'foreign' => 'id',
			'foreignTable' => 'strain',
			'onUpdate' => 'cascade',
			'onDelete' => '',
		));

		//$this->addIndex('cryopreservation', 'cryopreservation_strain_id', array( 'fields' => array( 0 => 'strain_id',),));
		//$this->addIndex('dna_extraction', 'dna_extraction_strain_id', array( 'fields' => array( 0 => 'strain_id',),));
		//$this->addIndex('isolation', 'isolation_strain_id', array( 'fields' => array( 0 => 'strain_id',),));
		//$this->addIndex('project', 'project_strain_id', array( 'fields' => array( 0 => 'strain_id',),));
	}

	public function down() {
		$this->dropForeignKey('cryopreservation', 'cryopreservation_strain_id_strain_id');
		$this->dropForeignKey('dna_extraction', 'dna_extraction_strain_id_strain_id');
		$this->dropForeignKey('isolation', 'isolation_strain_id_strain_id');
		$this->dropForeignKey('project', 'project_strain_id_strain_id');

		$this->createForeignKey('cryopreservation', 'cryopreservation_strain_id_strain_id', array(
			'name' => 'cryopreservation_strain_id_strain_id',
			'local' => 'strain_id',
			'foreign' => 'id',
			'foreignTable' => 'strain',
		));
		$this->createForeignKey('dna_extraction', 'dna_extraction_strain_id_strain_id', array(
			'name' => 'dna_extraction_strain_id_strain_id',
			'local' => 'strain_id',
			'foreign' => 'id',
			'foreignTable' => 'strain',
		));
		$this->createForeignKey('isolation', 'isolation_strain_id_strain_id', array(
			'name' => 'isolation_strain_id_strain_id',
			'local' => 'strain_id',
			'foreign' => 'id',
			'foreignTable' => 'strain',
		));
		$this->createForeignKey('project', 'project_strain_id_strain_id', array(
			'name' => 'project_strain_id_strain_id',
			'local' => 'strain_id',
			'foreign' => 'id',
			'foreignTable' => 'strain',
		));

		//$this->removeIndex('cryopreservation', 'cryopreservation_strain_id', array( 'fields' => array( 0 => 'strain_id',),));
		//$this->removeIndex('dna_extraction', 'dna_extraction_strain_id', array( 'fields' => array( 0 => 'strain_id',),));
		//$this->removeIndex('isolation', 'isolation_strain_id', array( 'fields' => array( 0 => 'strain_id',),));
		//$this->removeIndex('project', 'project_strain_id', array( 'fields' => array( 0 => 'strain_id',),));
	}
}
