<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version207 extends Doctrine_Migration_Base {
	public function up() {
		$this->addColumn('isolation', 'yearly_count', 'integer', '8', array('notnull' => '1'));
	}

	public function postUp() {
		$isolationTable = Doctrine_Core::getTable('Isolation');

		$isolations = $isolationTable->createQuery('i')->execute();
		foreach ($isolations as $isolation) {
			$year = date('Y', strtotime($isolation->getReceptionDate()));

			$minDate = sprintf('%s-01-01', $year);
			$maxDate = sprintf('%s-12-31', $year);
			$nextValue = $isolationTable->createQuery('i')
				->where('i.reception_date >= ?', $minDate)
				->andWhere('i.reception_date <= ?', $maxDate)
				->andWhere('i.yearly_count != 0')
				->count();
			$nextValue += 1;

			$isolation->setYearlyCount($nextValue);
			echo ">>\tYear: $year, count: $nextValue\n";
			$isolation->trySave();
		}
	}

	public function down() {
		$this->removeColumn('isolation', 'yearly_count');
	}
}
