<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version204 extends Doctrine_Migration_Base {
	public $patentDeposits = array();

	public function preUp() {
		echo ">> preUp() found ";

		$patentDepositTable = Doctrine_Core::getTable('PatentDeposit');
		$patentDepositTable->setColumn('depositor_code', 'string', 40, array('type' => 'string', 'length' => 40));
		$this->patentDeposits = $patentDepositTable->createQuery('p')
			->select('p.id, p.depositor_code')
			->execute(array(), Doctrine_Core::HYDRATE_SCALAR);

		echo count($this->patentDeposits);
		echo " patent deposits\n";
	}

	public function up() {
		echo ">> up(): dropping depositor_code from patent_deposit\n";
		$this->removeColumn('patent_deposit', 'depositor_code');
		echo ">> up(): adding yearly_count to patent_deposit\n";
		$this->addColumn('patent_deposit', 'yearly_count', 'integer', '8', array('notnull' => '1'));
	}

	public function postUp() {
		echo ">> postUp(): updating patent_deposit table\n";
		$patentDepositTable = Doctrine_Core::getTable('PatentDeposit');
		foreach ($this->patentDeposits as $patentDeposit) {
			$code = (int) preg_replace('/^BEA D(\d+)_(\d+)$/', "$1", $patentDeposit['p_depositor_code']);
			echo "{$patentDeposit['p_id']}: from {$patentDeposit['p_depositor_code']} to $code\n";
			$patentDepositTable->createQuery('p')
				->update()
				->set('p.yearly_count', $code)
				->where("p.id = ?", $patentDeposit['p_id'])
				->execute();
		}
	}

	public function down() {
		$this->addColumn('patent_deposit', 'depositor_code', 'string', '40', array('notnull' => '1'));
		$this->removeColumn('patent_deposit', 'yearly_count');
	}
}
