generator:
  class: sfDoctrineGenerator
  param:
    config:
      fields:
        updated_at:
          label: Last update
          date_format: f
      list:
        title: Roles
        display: [name, description, updated_at]
        sort: [name, asc]
      filter:
        display: [name]
      new:
        title: Add a new role