generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Radiation
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          radiation
    with_doctrine_route:   true
    actions_base_class:    MyActions
    css:  false

    config:
      actions: ~
      fields:
      list:
        title: Radiation types
        display: [name, nb_samples, updated_at]
        fields:
          nb_samples:
            label: Related samples
          updated_at:
            label: Last update
            date_format: f
        sort: [name, asc]
      filter:
        class: false
      form:
        fields:
          name:
            help: Type of radiation. This will appear in application lists
      edit:
        title: Edit "%%name%%" radiation type
      new:
        title: Create a new radiation type