generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Subkingdom
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          subkingdom
    with_doctrine_route:   true
    actions_base_class:    MyActions
    css:  false

    config:
      actions: ~
      fields:  ~
      list:
        title: Subkingdoms
        display: [name, updated_at]
        fields:
          name:
            label: Name
          updated_at:
            label: Last update
            date_format: f
        sort: ~
      filter:
        display: [name]
      form:    ~
      edit:    ~
      new:
        title: Add a new subkingdom
