generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Collector
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          collector
    with_doctrine_route:   true
    actions_base_class:    MyActions
    css:  false

    config:
      actions: ~
      fields: ~
      list:
        title: Collectors
        display: [name, surname, email, nb_samples, updated_at]
        fields:
          full_name:
            label: Name
          nb_samples:
            label: Samples collected
          updated_at:
            label: Last update
            date_format: f
        sort: ~
      filter:
        display: [name, surname, email]
      form:
        display:  [name, surname, email]
      edit:
        title: Edit "%%name%% %%surname%%"
      new:
        title: Add a new collector