generator:
  param:
    css:  false
    config:
      list:
        title:   Permissions
        display: [=name, description, updated_at]
        fields:
          updated_at: { label: Last update }

      edit:
        title: Editing permission "%%name%%"

      new:
        title: New permission