# Global options common to every model
actAs: [Timestampable]
options:
  type: INNODB

Country:
  columns:
    id:   { type: integer, primary: true, autoincrement: true }
    name: { type: string(255) }

Province:
  columns:
    id:         { type: integer, primary: true, autoincrement: true }
    name:       { type: string(255) }
    country_id: { type:integer, notnull:true }
  relations:
    Country:    { foreignAlias: Provinces }

EcosystemPicture:
  columns:
    id:           { type: integer, primary: true, autoincrement: true }
    filename:         { type: string(255), notnull: true }
    ecosystem_id: { type: integer, notnull: true }
  relations:
    Ecosystem:    { foreignAlias: Pictures, onDelete: cascade }

Ecosystem:
  columns:
    id:                 { type: integer, primary: true, autoincrement: true }
    name:               { type: string(255), notnull: true }
    latitude_degrees:   { type: integer }
    longitude_degrees:  { type: integer }
    latitude_minutes:   { type: float }
    longitude_minutes:  { type: float }
    country_id:         { type: integer, notnull: true }
    province_id:        { type: integer }
    city:               { type: string(255), notnull: true }
    remarks:            { type:string }
  relations:
    Country:            { foreignAlias: Ecosystems }
    Province:           { foreignAlias: Ecosystems }
    
Environment:
  columns:
    id:   { type: integer, primary: true, autoincrement: true }
    name: { type: string(255), notnull: true }

Habitat:
  columns:
    id:   { type: integer, primary: true, autoincrement: true }
    name: { type: string(255), notnull: true }

Role:
  columns:
    id:   { type: integer, primary: true, autoincrement: true }
    name: { type:string(255), notnull: true }

User:
  columns:
    id:       { type: integer, primary: true, autoincrement: true }
    username: { type:string(30), notnull: true }
    password: { type:string(30), notnull: true }
    name:     { type:string(255), notnull: true }
    surname:  { type:string(255), notnull: true }
    email:    { type:string(255), notnull:true }
    role_id:  { type:integer, notnull: true }
  relations:
    Role:     { foreignAlias: Users }
    
Sample:
  columns:
    id:                 { type: integer, primary: true, autoincrement: true }
    number:             { type: integer, notnull: true, unique: true, unsigned: true }
    ecosystem_id:       { type: integer, notnull: true }
    location:           { type: string(255), notnull: true }
    latitude_degrees:   { type: integer }
    longitude_degrees:  { type: integer }
    latitude_minutes:   { type: float }
    longitude_minutes:  { type: float }
    environment_id:     { type: integer, notnull: true }
    habitat_id:         { type: integer, notnull: true }
    ph:                 { type: float }
    conductivity:       { type: float }
    temperature:        { type: float }
    salinity:           { type: float }
    field_picture:      { type: string(255) }
    detailed_picture:   { type: string(255) }
    collector_id:       { type: integer, notnull: true }
    collection_date:    { type: timestamp, notnull: true }
    remarks:            { type: string }
  relations:
    Ecosystem:          { foreignAlias: Samples }
    Environment:        { foreignAlias: Samples }
    Habitat:            { foreignAlias: Samples }
    Collector:          { class: User, local: collector_id, foreignType: one, foreignAlias: Samples }