generator:
  param:
    css:  false
    config:
      list:
        title:   People
        display: [=username, name, email_address, last_login]
        fields:
          email_address: { label: Email }

      edit:
        title: Editing user "%%username%%"

      new:
        title: New user