generator:
  param:
    config:
      list:
        title:   People
        display: [=username, name, email_address, updated_at, last_login]
        fields:
          email_address: { label: Email }
          updated_at: { label: Last update }

      edit:
        title: Editing user "%%username%%"

      new:
        title: New user