generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Region
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          region
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
      list:
        title: Regions
        display: [code, name, nb_islands, nb_locations, updated_at]
        fields:
          nb_locations:
            label: Related locations
          nb_islands:
            label: Islands
          updated_at:
            label: Last update
            date_format: f
        sort: [code, asc]
      filter:
        display: [name]
      form:
        fields:
          name:
            help: This will appear in application lists
          code:
            help: Region code according to ISO 3166-2
          country_id:
            help: Country which the region belongs to
      edit:
        title: Edit "%%name%%"
      new:
        title: Add a new region